My Application: BGMDriven Class Reference
BGMDriven Class Reference
A class to handle the music, and allows the use of its function when other scenes are using it.
#include <BGMDriven.h>
Public Member Functions
BGMDriven ()
A default constructor, and the IrrKlang engine is being started right here
~BGMDriven ()
A destructor, and the IrrKlang engine is being dropped right here
void init ()
Where the initialization of the ISoundSource and ISound pointers begin.
void updatePlayerPos (vec3df pos, vec3df target, vec3df up)
An update function to update the player's position, target and up. Be warn that if this function is being updated too many times, it will cause inefficiency.
void playDarthVaderBackground ()
A method functions dedicated to just play Darth Vader theme as a background music
void playJohnCenaBackground ()
A method functions dedicated to just play John Cena theme as a background music
void playStarWarsThemeBackground ()
A method functions dedicated to just play Star Wars theme as a background music
void playWarpBackground ()
A method functions dedicated to just play Space Warp as a background music
void playPokemonBattleBackground ()
A method functions dedicated to just play Pokemon Battle theme as a background music
void playLovelyLullaby ()
A method functions dedicated to play a Lullaby as a background music
void playGateEffect (vec3df pos)
A method functions dedicated to just play the 3D gate sound effect
void playIamYourFatherEffect (vec3df pos)
A method functions dedicated to just play the 3D effect of 'I am Your Father'
void playJoinDarkSideEffect (vec3df pos)
A method functions dedicated to just play the 3D effect of 'Join the Dark Side'
void stopAllSound ()
A method functions to stop all sounds
Private Member Functions
bool soundEffectArePlaying ()
return true / false if the sound effects are being played
Private Attributes
ISoundEngine * engine
ISoundSource * DarthVaderbackGround
ISoundSource * GateEffectSource
ISoundSource * StarWarsTheme
ISoundSource * PokemonGymBattleSource
ISoundSource * SpaceWarpSource
ISoundSource * john_cenaSource
ISoundSource * i_amYourFather
ISoundSource * join_DarkSide
ISoundSource * LovelyLullabySource
ISound * ZeBackgroundMusic
ISound * GateEffect
ISound * iamYourFatherEffect
ISound * join_DarkSideEffect
bool playIAmYourFatherOnce
bool playJoinDarkSideOnce
Detailed Description
A class to handle the music, and allows the use of its function when other scenes are using it.
Class BGMDriven:
Definition at line 26 of file BGMDriven.h.
Constructor & Destructor Documentation
BGMDriven::BGMDriven ()
A default constructor, and the IrrKlang engine is being started right here
Definition at line 8 of file BGMDriven.cpp.
References irrklang::createIrrKlangDevice(), and engine.
BGMDriven::~BGMDriven ()
A destructor, and the IrrKlang engine is being dropped right here
Definition at line 22 of file BGMDriven.cpp.
References irrklang::IRefCounted::drop(), and engine.
Member Function Documentation
void BGMDriven::init ()
Where the initialization of the ISoundSource and ISound pointers begin.
Definition at line 32 of file BGMDriven.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), DarthVaderbackGround, engine, GateEffect, GateEffectSource, i_amYourFather, iamYourFatherEffect, john_cenaSource, join_DarkSide, join_DarkSideEffect, LovelyLullabySource, irrklang::ISoundEngine::play2D(), irrklang::ISoundEngine::play3D(), PokemonGymBattleSource, irrklang::ISoundSource::setDefaultVolume(), SpaceWarpSource, StarWarsTheme, and ZeBackgroundMusic.
Referenced by Application::Run().
void BGMDriven::playDarthVaderBackground ()
A method functions dedicated to just play Darth Vader theme as a background music
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 74 of file BGMDriven.cpp.
References DarthVaderbackGround, engine, irrklang::ISoundEngine::isCurrentlyPlaying(), irrklang::ISoundEngine::play2D(), irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene2_SP2::Ending(), and sceneSP2::Update().
void BGMDriven::playGateEffect (vec3df pos)
A method functions dedicated to just play the 3D gate sound effect
Parameters
pos - the position of the Gate
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 92 of file BGMDriven.cpp.
References engine, GateEffect, GateEffectSource, irrklang::ISound::getIsPaused(), irrklang::ISound::isFinished(), irrklang::ISoundEngine::play3D(), irrklang::ISound::setIsPaused(), irrklang::ISound::setPosition(), irrklang::ISound::setVolume(), and ZeBackgroundMusic.
Referenced by sceneSP2::Update().
void BGMDriven::playIamYourFatherEffect (vec3df pos)
A method functions dedicated to just play the 3D effect of 'I am Your Father'
Parameters
pos - the position of the object which will play out this sound
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 196 of file BGMDriven.cpp.
References engine, irrklang::ISound::getIsPaused(), i_amYourFather, iamYourFatherEffect, irrklang::ISound::isFinished(), irrklang::ISoundEngine::play3D(), playIAmYourFatherOnce, irrklang::ISound::setIsPaused(), irrklang::ISound::setPosition(), irrklang::ISound::setVolume(), and ZeBackgroundMusic.
Referenced by scene2_SP2::renderDeadPool().
void BGMDriven::playJohnCenaBackground ()
A method functions dedicated to just play John Cena theme as a background music
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 130 of file BGMDriven.cpp.
References engine, irrklang::ISoundEngine::isCurrentlyPlaying(), john_cenaSource, irrklang::ISoundEngine::play2D(), irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene2_SP2::VaultAnimation().
void BGMDriven::playJoinDarkSideEffect (vec3df pos)
A method functions dedicated to just play the 3D effect of 'Join the Dark Side'
Parameters
pos - position of the object to play this sound
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 220 of file BGMDriven.cpp.
References engine, irrklang::ISound::getIsPaused(), irrklang::ISound::isFinished(), join_DarkSide, join_DarkSideEffect, irrklang::ISoundEngine::play3D(), playJoinDarkSideOnce, irrklang::ISound::setIsPaused(), irrklang::ISound::setPosition(), irrklang::ISound::setVolume(), and ZeBackgroundMusic.
Referenced by scene2_SP2::renderDeadPool().
void BGMDriven::playLovelyLullaby ()
A method functions dedicated to play a Lullaby as a background music
Exceptions
- if the source file cannot be found, nothing is played
Definition at line 269 of file BGMDriven.cpp.
References engine, irrklang::ISoundEngine::isCurrentlyPlaying(), LovelyLullabySource, irrklang::ISoundEngine::play2D(), irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene2_SP2::Update().
void BGMDriven::playPokemonBattleBackground ()
A method functions dedicated to just play Pokemon Battle theme as a background music
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 146 of file BGMDriven.cpp.
References engine, irrklang::ISoundEngine::isCurrentlyPlaying(), irrklang::ISoundEngine::play2D(), PokemonGymBattleSource, irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene3_SP2::Update().
void BGMDriven::playStarWarsThemeBackground ()
A method functions dedicated to just play Star Wars theme as a background music
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 162 of file BGMDriven.cpp.
References engine, irrklang::ISoundEngine::isCurrentlyPlaying(), irrklang::ISoundEngine::play2D(), StarWarsTheme, irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene2_SP2::rollingCredits().
void BGMDriven::playWarpBackground ()
A method functions dedicated to just play Space Warp as a background music
Exceptions
- if the source file of the music cannot be found, nothing is played
Definition at line 178 of file BGMDriven.cpp.
References engine, irrklang::ISoundEngine::isCurrentlyPlaying(), irrklang::ISoundEngine::play2D(), SpaceWarpSource, irrklang::ISound::stop(), and ZeBackgroundMusic.
Referenced by scene3_SP2::animateWarp().
bool BGMDriven::soundEffectArePlaying () private
return true / false if the sound effects are being played
Returns
true - if either 1 of the sound effects are being played
false - if no sound effect is played
Definition at line 244 of file BGMDriven.cpp.
References engine, GateEffectSource, i_amYourFather, irrklang::ISoundEngine::isCurrentlyPlaying(), and join_DarkSide.
void BGMDriven::stopAllSound ()
A method functions to stop all sounds
Definition at line 258 of file BGMDriven.cpp.
References engine, and irrklang::ISoundEngine::stopAllSounds().
void BGMDriven::updatePlayerPos (vec3df pos, vec3df target, vec3df up)
An update function to update the player's position, target and up. Be warn that if this function is being updated too many times, it will cause inefficiency.
Parameters
pos - position of the player
target - target of / where the player is looking at
up - the up vector of the player.
Definition at line 119 of file BGMDriven.cpp.
References engine, and irrklang::ISoundEngine::setListenerPosition().
Referenced by scene2_SP2::Update(), and sceneSP2::Update().
Field Documentation
ISoundSource* BGMDriven::DarthVaderbackGround private
Definition at line 55 of file BGMDriven.h.
Referenced by init(), and playDarthVaderBackground().
ISoundEngine* BGMDriven::engine private
Definition at line 54 of file BGMDriven.h.
Referenced by BGMDriven(), init(), playDarthVaderBackground(), playGateEffect(), playIamYourFatherEffect(), playJohnCenaBackground(), playJoinDarkSideEffect(), playLovelyLullaby(), playPokemonBattleBackground(), playStarWarsThemeBackground(), playWarpBackground(), soundEffectArePlaying(), stopAllSound(), updatePlayerPos(), and ~BGMDriven().
ISound* BGMDriven::GateEffect private
Definition at line 67 of file BGMDriven.h.
Referenced by init(), and playGateEffect().
ISoundSource* BGMDriven::GateEffectSource private
Definition at line 56 of file BGMDriven.h.
Referenced by init(), playGateEffect(), and soundEffectArePlaying().
ISoundSource* BGMDriven::i_amYourFather private
Definition at line 61 of file BGMDriven.h.
Referenced by init(), playIamYourFatherEffect(), and soundEffectArePlaying().
ISound* BGMDriven::iamYourFatherEffect private
Definition at line 68 of file BGMDriven.h.
Referenced by init(), and playIamYourFatherEffect().
ISoundSource* BGMDriven::john_cenaSource private
Definition at line 60 of file BGMDriven.h.
Referenced by init(), and playJohnCenaBackground().
ISoundSource* BGMDriven::join_DarkSide private
Definition at line 62 of file BGMDriven.h.
Referenced by init(), playJoinDarkSideEffect(), and soundEffectArePlaying().
ISound* BGMDriven::join_DarkSideEffect private
Definition at line 69 of file BGMDriven.h.
Referenced by init(), and playJoinDarkSideEffect().
ISoundSource* BGMDriven::LovelyLullabySource private
Definition at line 63 of file BGMDriven.h.
Referenced by init(), and playLovelyLullaby().
bool BGMDriven::playIAmYourFatherOnce private
Definition at line 72 of file BGMDriven.h.
Referenced by playIamYourFatherEffect().
bool BGMDriven::playJoinDarkSideOnce private
Definition at line 73 of file BGMDriven.h.
Referenced by playJoinDarkSideEffect().
ISoundSource* BGMDriven::PokemonGymBattleSource private
Definition at line 58 of file BGMDriven.h.
Referenced by init(), and playPokemonBattleBackground().
ISoundSource* BGMDriven::SpaceWarpSource private
Definition at line 59 of file BGMDriven.h.
Referenced by init(), and playWarpBackground().
ISoundSource* BGMDriven::StarWarsTheme private
Definition at line 57 of file BGMDriven.h.
Referenced by init(), and playStarWarsThemeBackground().
ISound* BGMDriven::ZeBackgroundMusic private
Definition at line 66 of file BGMDriven.h.
Referenced by init(), playDarthVaderBackground(), playGateEffect(), playIamYourFatherEffect(), playJohnCenaBackground(), playJoinDarkSideEffect(), playLovelyLullaby(), playPokemonBattleBackground(), playStarWarsThemeBackground(), and playWarpBackground().
The documentation for this class was generated from the following files:
MyGraphics/Source/BGMDriven.h
MyGraphics/Source/BGMDriven.cpp