My Application: scene2_SP2 Class Reference
scene2_SP2 Class Reference
inheirited from Scene and made improvised to it. To turn it into a game. This is Scenario 3
#include <scene2_SP2.h>
Public Member Functions
scene2_SP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
~scene2_SP2 ()
destructor
virtual void Init ()
initializing whatever is needed for the scene
virtual void Update (double dt)
where the logic of the game is, and update
virtual void Render ()
where the rendering of all the stuff we needed will be here
virtual void Exit ()
cleans up the scene
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_LIGHTBALL, GEO_COMIC_TEXT, GEO_LANDVEHICLE,
GEO_FLYINGVEHICLE, GEO_ROBOT, GEO_SPACESHUTTLE, GEO_VAULTCUBE,
GEO_VAULTWHEEL, GEO_VAULTSTICK, GEO_VAULTDOOR, GEO_NUMPAD,
GEO_NUMROLL, GEO_ARROW, GEO_SATELLITEHEAD, GEO_SATELLITEBODY,
GEO_BIGDIAMOND, GEO_SMALLDIAMOND, GEO_BIGDIAMOND2, GEO_SMALLDIAMOND2,
GEO_NPCUPPER, GEO_NPCLOWER, GEO_ASTEROID, GEO_ASTEROID2,
GEO_NPCROBOT, GEO_PLANET_SKYBOX, GEO_PLANET_GROUND, GEO_UI,
GEO_BOXES, GEO_NORMALBOXES, GEO_DEADPOOL, GEO_TEXT_BOX,
GEO_ENDING_SCREEN, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
rendering of the meshes
void RenderSkybox ()
rendering sky box
void RenderRobot ()
a method to render Rot Civ and it's dialogue
void RenderFlyingVehicle ()
rendering flying vehicle
void RenderLandingVehicle ()
rendering landing vehicle
void RenderSpaceShuttle ()
rendering space shuttle
void RenderVault ()
rendering vault
void RenderNumpad ()
rendering numpad
void RenderNumroll ()
void RenderMenu ()
void RenderArrow ()
rendering numpad's pointing arrow
void RenderSatellite ()
rendering satellite
void RenderDiamond ()
rendering diamonds
void RenderNPC ()
rendering robot npcs
void RenderBoxes ()
rendering blue boxes
void RenderPlane ()
void RenderAsteroid ()
rendering asteroids
void VaultAnimation (double dt)
vault animation
void SatelliteAnimation (double dt)
satellite animation
void diamondAnimation (double dt)
diamond animation
void NPCAnimation (double dt)
robot NPCs animation
void BoxesAnimation (double dt)
boxes animation
void Reset ()
Reset whole scene2 to default.
void RenderText (Mesh *mesh, std::string text, Color color)
rendering of the texts using quads
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
rendering of the texts using quads on screen
void RenderNumPadOnScreen (Mesh *mesh, float size, float x, float y, float z, float rotate, float rotatex, float rotatey)
rendering numpad on screen
void RenderImageOnScreen (Mesh *mesh, float size, float x, float y)
rendering of image using quad on screen
void RenderImageOnScreen (Mesh *mesh, float x, float y, float sizeX, float sizeY)
a method to render a non-uniform scalling image on screen
void RenderUserInterface (Mesh *mesh, float size, float x, float y)
rendering user interface
void renderDeadPool ()
a method to render Deadpool and his dialogues
void renderDialogueBox (const string &name, const string &dialogue)
a method to render dialogue box with the object's name and dialogue
void Ending (double &dt)
the logic behind animating the ending
void renderEndingScreen ()
a method to render the ending screen
void rollingCredits ()
a method to render the credits
void renderIntruction ()
Private Attributes
bool on_light
bool wheelturn
bool stickpush
bool dooropen
bool satelliterotate
bool bigdiamondtranslate
bool bigdiamondrotate
bool smalldiamondtranslate
bool smalldiamondrotate
bool NPCrotate
bool NPCrotate2
bool NPCrotate3
bool boxesappear
bool boxesappear2
bool boxesappear3
bool boxestransfer
bool change
bool change2
bool change3
float LSPEED = 10.f
float wheelturning
float stickpushing
float dooropening
float satelliterotating
float bigdiamondtranslating
float bigdiamondrotating
float smalldiamondtranslating
float smalldiamondrotating
float NPCrotating
float NPCrotating2
float NPCrotating3
float boxesrotating
float boxesrotating2
float boxesrotating3
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Light light [2]
Camera3 camera
NumPad Numpad
NPC robotNPC1
NPC robotNPC2
NPC robotNPC3
NPC vault
MS modelStack
MS viewStack
MS projectionStack
double framePerSecond
float screenWidth
float screenHeight
rot_civ Rot_Civ_
bool beginEnding
bool beginIamYourFather
double endingTime
float moveToDeadPoolZ
float sizeofEndingScreen
creditScene creditRolling
double update3DPos
double PreventSpammingInstruction
bool displayInstruction
Detailed Description
inheirited from Scene and made improvised to it. To turn it into a game. This is Scenario 3
Class scene2_SP2:
Definition at line 33 of file scene2_SP2.h.
Member Enumeration Documentation
enum scene2_SP2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LIGHTBALL
GEO_COMIC_TEXT
GEO_LANDVEHICLE
GEO_FLYINGVEHICLE
GEO_ROBOT
GEO_SPACESHUTTLE
GEO_VAULTCUBE
GEO_VAULTWHEEL
GEO_VAULTSTICK
GEO_VAULTDOOR
GEO_NUMPAD
GEO_NUMROLL
GEO_ARROW
GEO_SATELLITEHEAD
GEO_SATELLITEBODY
GEO_BIGDIAMOND
GEO_SMALLDIAMOND
GEO_BIGDIAMOND2
GEO_SMALLDIAMOND2
GEO_NPCUPPER
GEO_NPCLOWER
GEO_ASTEROID
GEO_ASTEROID2
GEO_NPCROBOT
GEO_PLANET_SKYBOX
GEO_PLANET_GROUND
GEO_UI
GEO_BOXES
GEO_NORMALBOXES
GEO_DEADPOOL
GEO_TEXT_BOX
GEO_ENDING_SCREEN
NUM_GEOMETRY
Definition at line 35 of file scene2_SP2.h.
enum scene2_SP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 106 of file scene2_SP2.h.
Constructor & Destructor Documentation
scene2_SP2::scene2_SP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
Parameters
screenwidth - width of the screen
screenheight - height of the screen
Definition at line 27 of file scene2_SP2.cpp.
scene2_SP2::~scene2_SP2 ()
destructor
Definition at line 36 of file scene2_SP2.cpp.
Member Function Documentation
void scene2_SP2::BoxesAnimation (double dt) private
boxes animation
Parameters
dt - time frame
Definition at line 2316 of file scene2_SP2.cpp.
References boxesappear, boxesappear2, boxesappear3, boxesrotating, boxesrotating2, boxesrotating3, NPC::get_LineOfDialogue(), NPC::interaction(), and robotNPC2.
Referenced by Update().
void scene2_SP2::diamondAnimation (double dt) private
diamond animation
Parameters
dt - time frame
Definition at line 2164 of file scene2_SP2.cpp.
References bigdiamondrotating, bigdiamondtranslate, bigdiamondtranslating, smalldiamondrotating, smalldiamondtranslate, and smalldiamondtranslating.
Referenced by Update().
void scene2_SP2::Ending (double & dt) private
the logic behind animating the ending
Parameters
dt - frame time
Definition at line 2470 of file scene2_SP2.cpp.
References creditScene::activateCredit(), beginIamYourFather, camera, creditRolling, Vector3::Cross(), Camera3::defaultPosition, Camera3::defaultUp, Math::DegreeToRadian(), endingTime, Camera3::getCameraXrotation(), Camera3::getCameraYrotation(), moveToDeadPoolZ, Application::musics, BGMDriven::playDarthVaderBackground(), Camera::position, Camera3::setLocation(), Camera3::setRotation(), sizeofEndingScreen, Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void scene2_SP2::Exit () virtual
cleans up the scene
Implements Scene.
Definition at line 734 of file scene2_SP2.cpp.
References m_programID, and m_vertexArrayID.
void scene2_SP2::Init () virtual
initializing whatever is needed for the scene
Implements Scene.
Definition at line 45 of file scene2_SP2.cpp.
References beginEnding, beginIamYourFather, bigdiamondrotate, bigdiamondrotating, bigdiamondtranslate, bigdiamondtranslating, boxesappear, boxesappear2, boxesappear3, boxesrotating, boxesrotating2, boxesrotating3, boxestransfer, camera, Camera3::camType, change, change2, change3, Light::color, Light::cosCutoff, Light::cosInner, creditRolling, Camera3::cursorCoordX, Camera3::cursorCoordY, Math::DegreeToRadian(), displayInstruction, dooropen, dooropening, endingTime, Light::exponent, Camera3::FIRST_PERSON, framePerSecond, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ARROW, GEO_ASTEROID, GEO_ASTEROID2, GEO_AXES, GEO_BIGDIAMOND, GEO_BIGDIAMOND2, GEO_BOXES, GEO_COMIC_TEXT, GEO_DEADPOOL, GEO_ENDING_SCREEN, GEO_FLYINGVEHICLE, GEO_LANDVEHICLE, GEO_LIGHTBALL, GEO_NORMALBOXES, GEO_NPCLOWER, GEO_NPCROBOT, GEO_NPCUPPER, GEO_NUMPAD, GEO_NUMROLL, GEO_PLANET_GROUND, GEO_PLANET_SKYBOX, GEO_ROBOT, GEO_SATELLITEBODY, GEO_SATELLITEHEAD, GEO_SMALLDIAMOND, GEO_SMALLDIAMOND2, GEO_SPACESHUTTLE, GEO_TEXT_BOX, GEO_UI, GEO_VAULTCUBE, GEO_VAULTDOOR, GEO_VAULTSTICK, GEO_VAULTWHEEL, objectsForDisplay::init(), NPC::Init(), NumPad::Init(), Camera3::Init(), creditScene::initCredit(), rot_civ::InitDialogues(), Camera3::InitObjects(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, moveToDeadPoolZ, NPCrotate, NPCrotate2, NPCrotate3, NPCrotating, NPCrotating2, NPCrotating3, Numpad, on_light, Light::position, Light::power, PreventSpammingInstruction, projectionStack, robotNPC1, robotNPC2, robotNPC3, Rot_Civ_, satelliterotate, satelliterotating, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Mtx44::SetToPerspective(), sizeofEndingScreen, smalldiamondrotate, smalldiamondrotating, smalldiamondtranslate, smalldiamondtranslating, Light::spotDirection, stickpush, stickpushing, Camera3::storage_of_objects, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, update3DPos, vault, wheelturn, and wheelturning.
void scene2_SP2::NPCAnimation (double dt) private
robot NPCs animation
Parameters
dt - time frame
Definition at line 2214 of file scene2_SP2.cpp.
References change, change2, change3, NPC::get_LineOfDialogue(), NPC::interaction(), NPCrotate, NPCrotate2, NPCrotate3, NPCrotating, NPCrotating2, NPCrotating3, and robotNPC2.
Referenced by Update().
void scene2_SP2::Render () virtual
where the rendering of all the stuff we needed will be here
Implements Scene.
Definition at line 520 of file scene2_SP2.cpp.
References beginIamYourFather, camera, NumPad::displayerror(), displayInstruction, framePerSecond, GEO_ARROW, GEO_COMIC_TEXT, GEO_NUMPAD, GEO_NUMROLL, GEO_PLANET_GROUND, GEO_TEXT_BOX, NumPad::getarrowposition(), Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), NumPad::getfirstrotate(), NumPad::getfourthrotate(), NumPad::getsecondrotate(), NumPad::getthirdrotate(), NumPad::interactiontext(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, moveToDeadPoolZ, Numpad, NumPad::NumpadRenderOnScreen(), on_light, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderAsteroid(), RenderBoxes(), renderDeadPool(), renderDialogueBox(), RenderDiamond(), renderEndingScreen(), RenderFlyingVehicle(), RenderImageOnScreen(), RenderLandingVehicle(), renderMesh(), RenderNPC(), RenderNumpad(), RenderNumPadOnScreen(), RenderRobot(), RenderSatellite(), RenderSkybox(), RenderSpaceShuttle(), RenderTextOnScreen(), RenderVault(), rollingCredits(), MS::Scale(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void scene2_SP2::RenderArrow () private
rendering numpad's pointing arrow
Definition at line 1262 of file scene2_SP2.cpp.
References camera, GEO_ARROW, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
void scene2_SP2::RenderAsteroid () private
rendering asteroids
Definition at line 1857 of file scene2_SP2.cpp.
References camera, GEO_ASTEROID, GEO_ASTEROID2, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderBoxes () private
rendering blue boxes
Definition at line 1738 of file scene2_SP2.cpp.
References boxesrotating, boxesrotating2, boxesrotating3, camera, change, change2, change3, GEO_BOXES, GEO_NORMALBOXES, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::renderDeadPool () private
a method to render Deadpool and his dialogues
Definition at line 2381 of file scene2_SP2.cpp.
References beginIamYourFather, camera, endingTime, GEO_DEADPOOL, meshList, modelStack, Application::musics, BGMDriven::playIamYourFatherEffect(), BGMDriven::playJoinDarkSideEffect(), MS::PopMatrix(), Camera::position, MS::PushMatrix(), renderDialogueBox(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void scene2_SP2::renderDialogueBox (const string & name, const string & dialogue) private
a method to render dialogue box with the object's name and dialogue
Parameters
name - name of the interacted object
dialogue - dialogue return by the interacted object
Definition at line 2456 of file scene2_SP2.cpp.
References GEO_COMIC_TEXT, GEO_TEXT_BOX, meshList, RenderImageOnScreen(), and RenderTextOnScreen().
Referenced by Render(), renderDeadPool(), RenderNPC(), RenderRobot(), and RenderVault().
void scene2_SP2::RenderDiamond () private
rendering diamonds
Definition at line 1347 of file scene2_SP2.cpp.
References bigdiamondrotating, bigdiamondtranslating, camera, GEO_BIGDIAMOND, GEO_BIGDIAMOND2, GEO_SMALLDIAMOND, GEO_SMALLDIAMOND2, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), smalldiamondrotating, smalldiamondtranslating, Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::renderEndingScreen () private
a method to render the ending screen
Definition at line 2511 of file scene2_SP2.cpp.
References GEO_ENDING_SCREEN, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderImageOnScreen(), and sizeofEndingScreen.
Referenced by Render().
void scene2_SP2::RenderFlyingVehicle () private
rendering flying vehicle
Definition at line 976 of file scene2_SP2.cpp.
References camera, GEO_FLYINGVEHICLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderImageOnScreen (Mesh * mesh, float size, float x, float y) private
rendering of image using quad on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 843 of file scene2_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render(), renderDialogueBox(), and renderEndingScreen().
void scene2_SP2::RenderImageOnScreen (Mesh * mesh, float x, float y, float sizeX, float sizeY) private
a method to render a non-uniform scalling image on screen
Parameters
mesh - the shape that will be rendered
x - x coordinate of image
y - y coordinate of image
sizeX - scalling of image based on the X-axis
sizeY - scalling of image based on the Y-axis
Definition at line 2424 of file scene2_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
void scene2_SP2::renderIntruction () private
void scene2_SP2::RenderLandingVehicle () private
rendering landing vehicle
Definition at line 1000 of file scene2_SP2.cpp.
References camera, GEO_LANDVEHICLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderMenu () private
void scene2_SP2::renderMesh (Mesh * mesh, bool enableLight) private
rendering of the meshes
Parameters
mesh - the specific mesh
enableLight - to enable lighting on the object
Definition at line 472 of file scene2_SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderArrow(), RenderAsteroid(), RenderBoxes(), renderDeadPool(), RenderDiamond(), RenderFlyingVehicle(), RenderImageOnScreen(), RenderLandingVehicle(), RenderNPC(), RenderNumpad(), RenderNumPadOnScreen(), RenderRobot(), RenderSatellite(), RenderSkybox(), RenderSpaceShuttle(), RenderUserInterface(), and RenderVault().
void scene2_SP2::RenderNPC () private
rendering robot npcs
Definition at line 1591 of file scene2_SP2.cpp.
References camera, GEO_NPCLOWER, GEO_NPCROBOT, GEO_NPCUPPER, NPC::getDialogue(), NPC::interaction(), Application::IsKeyPressed(), meshList, modelStack, NPC::NPC_getposition_x(), NPC::NPC_getposition_y(), NPC::NPC_getposition_z(), NPCrotating, NPCrotating2, NPCrotating3, MS::PopMatrix(), MS::PushMatrix(), renderDialogueBox(), renderMesh(), robotNPC1, robotNPC2, robotNPC3, MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderNumpad () private
rendering numpad
Definition at line 1157 of file scene2_SP2.cpp.
References camera, dooropening, GEO_NUMPAD, GEO_NUMROLL, NumPad::getfirstrotate(), NumPad::getfourthrotate(), NumPad::getsecondrotate(), NumPad::getthirdrotate(), meshList, modelStack, Numpad, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderNumPadOnScreen (Mesh * mesh, float size, float x, float y, float z, float rotate, float rotatex, float rotatey) private
rendering numpad on screen
Parameters
mesh - a pointer to the specific mesh
size - size of the numroll
x - x coordinate of the numroll
y - y coordinate of the numroll
z - z coordinate of the numroll
rotate - rotate angle of the numroll
rotatex - rotate x coordinate of the numroll
rotatey - rotate y coordinate of the numroll
Definition at line 881 of file scene2_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render().
void scene2_SP2::RenderNumroll () private
void scene2_SP2::RenderPlane () private
void scene2_SP2::RenderRobot () private
a method to render Rot Civ and it's dialogue
Definition at line 956 of file scene2_SP2.cpp.
References GEO_ROBOT, GameObject::getName(), objectsForDisplay::getObjectposX(), objectsForDisplay::getObjectposY(), objectsForDisplay::getObjectposZ(), rot_civ::interaction(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderDialogueBox(), renderMesh(), rot_civ::returnDialogue(), Rot_Civ_, MS::Scale(), and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderSatellite () private
rendering satellite
Definition at line 1285 of file scene2_SP2.cpp.
References camera, GEO_SATELLITEBODY, GEO_SATELLITEHEAD, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), satelliterotating, MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderSkybox () private
rendering sky box
Definition at line 909 of file scene2_SP2.cpp.
References GEO_PLANET_SKYBOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), and renderMesh().
Referenced by Render().
void scene2_SP2::RenderSpaceShuttle () private
rendering space shuttle
Definition at line 1022 of file scene2_SP2.cpp.
References camera, GEO_SPACESHUTTLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene2_SP2::RenderText (Mesh * mesh, std::string text, Color color) private
rendering of the texts using quads
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
Definition at line 750 of file scene2_SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void scene2_SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
rendering of the texts using quads on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 790 of file scene2_SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), renderDialogueBox(), and rollingCredits().
void scene2_SP2::RenderUserInterface (Mesh * mesh, float size, float x, float y) private
rendering user interface
Parameters
mesh - a pointer to the specific mesh
size - size of the interface
x - x coordinate of the interface
y - y coordinate of the interface
Definition at line 927 of file scene2_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
void scene2_SP2::RenderVault () private
rendering vault
Definition at line 1044 of file scene2_SP2.cpp.
References camera, dooropening, GEO_VAULTCUBE, GEO_VAULTDOOR, GEO_VAULTSTICK, GEO_VAULTWHEEL, NPC::getDialogue(), NPC::interaction(), NumPad::interactiontext(), Application::IsKeyPressed(), meshList, modelStack, NPC::NPC_getposition_x(), NPC::NPC_getposition_y(), NPC::NPC_getposition_z(), Numpad, MS::PopMatrix(), MS::PushMatrix(), renderDialogueBox(), renderMesh(), MS::Rotate(), MS::Scale(), stickpushing, Camera3::storage_of_objects, MS::Translate(), vault, and wheelturning.
Referenced by Render().
void scene2_SP2::Reset () private
Reset whole scene2 to default.
Definition at line 2548 of file scene2_SP2.cpp.
References beginEnding, beginIamYourFather, boxesappear3, camera, change3, creditRolling, dooropen, dooropening, endingTime, moveToDeadPoolZ, NPCrotate3, NPCrotating3, Numpad, NumPad::Reset(), creditScene::reset(), Camera3::Reset(), sizeofEndingScreen, stickpush, stickpushing, wheelturn, and wheelturning.
Referenced by Update().
void scene2_SP2::rollingCredits () private
a method to render the credits
Definition at line 2522 of file scene2_SP2.cpp.
References creditRolling, GEO_COMIC_TEXT, creditScene::getMovePositionY(), creditScene::getRollingTitle(), creditScene::getRollingTitleCaption(), creditScene::goRollCredit(), meshList, Application::musics, creditScene::names, BGMDriven::playStarWarsThemeBackground(), creditScene::position, and RenderTextOnScreen().
Referenced by Render().
void scene2_SP2::SatelliteAnimation (double dt) private
satellite animation
Parameters
dt - time frame
Definition at line 2135 of file scene2_SP2.cpp.
References satelliterotate, and satelliterotating.
Referenced by Update().
void scene2_SP2::Update (double dt) virtual
where the logic of the game is, and update
Parameters
dt - time frame
Implements Scene.
Definition at line 378 of file scene2_SP2.cpp.
References beginEnding, beginIamYourFather, BoxesAnimation(), camera, Application::changeIntoScenario1(), Application::changeIntoScenario2(), creditRolling, diamondAnimation(), displayInstruction, dooropening, Ending(), framePerSecond, creditScene::goRollCredit(), Application::IsKeyPressed(), Application::musics, NPCAnimation(), Numpad, NumPad::NumpadProgram(), NumPad::NumpadRenderOnScreen(), NumPad::NumpadVerify(), BGMDriven::playLovelyLullaby(), Camera::position, PreventSpammingInstruction, Reset(), robotNPC1, robotNPC2, robotNPC3, Rot_Civ_, SatelliteAnimation(), Camera::target, Camera::up, rot_civ::update(), NumPad::Update(), NPC::update(), Camera3::Update(), update3DPos, creditScene::updateCredit(), BGMDriven::updatePlayerPos(), vault, VaultAnimation(), Vector3::x, Vector3::y, and Vector3::z.
void scene2_SP2::VaultAnimation (double dt) private
vault animation
Parameters
dt - time frame
Definition at line 2073 of file scene2_SP2.cpp.
References dooropen, dooropening, Application::musics, Numpad, NumPad::NumpadVerify(), BGMDriven::playJohnCenaBackground(), stickpush, stickpushing, and wheelturning.
Referenced by Update().
Field Documentation
bool scene2_SP2::beginEnding private
Definition at line 264 of file scene2_SP2.h.
Referenced by Init(), Reset(), and Update().
bool scene2_SP2::beginIamYourFather private
Definition at line 265 of file scene2_SP2.h.
Referenced by Ending(), Init(), Render(), renderDeadPool(), Reset(), and Update().
bool scene2_SP2::bigdiamondrotate private
Definition at line 168 of file scene2_SP2.h.
Referenced by Init().
float scene2_SP2::bigdiamondrotating private
Definition at line 188 of file scene2_SP2.h.
Referenced by diamondAnimation(), Init(), and RenderDiamond().
bool scene2_SP2::bigdiamondtranslate private
Definition at line 167 of file scene2_SP2.h.
Referenced by diamondAnimation(), and Init().
float scene2_SP2::bigdiamondtranslating private
Definition at line 187 of file scene2_SP2.h.
Referenced by diamondAnimation(), Init(), and RenderDiamond().
bool scene2_SP2::boxesappear private
Definition at line 174 of file scene2_SP2.h.
Referenced by BoxesAnimation(), and Init().
bool scene2_SP2::boxesappear2 private
Definition at line 175 of file scene2_SP2.h.
Referenced by BoxesAnimation(), and Init().
bool scene2_SP2::boxesappear3 private
Definition at line 176 of file scene2_SP2.h.
Referenced by BoxesAnimation(), Init(), and Reset().
float scene2_SP2::boxesrotating private
Definition at line 194 of file scene2_SP2.h.
Referenced by BoxesAnimation(), Init(), and RenderBoxes().
float scene2_SP2::boxesrotating2 private
Definition at line 195 of file scene2_SP2.h.
Referenced by BoxesAnimation(), Init(), and RenderBoxes().
float scene2_SP2::boxesrotating3 private
Definition at line 196 of file scene2_SP2.h.
Referenced by BoxesAnimation(), Init(), and RenderBoxes().
bool scene2_SP2::boxestransfer private
Definition at line 177 of file scene2_SP2.h.
Referenced by Init().
Camera3 scene2_SP2::camera private
Definition at line 232 of file scene2_SP2.h.
Referenced by Ending(), Init(), Render(), RenderArrow(), RenderAsteroid(), RenderBoxes(), renderDeadPool(), RenderDiamond(), RenderFlyingVehicle(), RenderLandingVehicle(), RenderNPC(), RenderNumpad(), RenderSatellite(), RenderSpaceShuttle(), RenderVault(), Reset(), and Update().
bool scene2_SP2::change private
Definition at line 178 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), and RenderBoxes().
bool scene2_SP2::change2 private
Definition at line 179 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), and RenderBoxes().
bool scene2_SP2::change3 private
Definition at line 180 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), RenderBoxes(), and Reset().
creditScene scene2_SP2::creditRolling private
Definition at line 273 of file scene2_SP2.h.
Referenced by Ending(), Init(), Reset(), rollingCredits(), and Update().
bool scene2_SP2::displayInstruction private
Definition at line 287 of file scene2_SP2.h.
Referenced by Init(), Render(), and Update().
bool scene2_SP2::dooropen private
Definition at line 165 of file scene2_SP2.h.
Referenced by Init(), Reset(), and VaultAnimation().
float scene2_SP2::dooropening private
Definition at line 185 of file scene2_SP2.h.
Referenced by Init(), RenderNumpad(), RenderVault(), Reset(), Update(), and VaultAnimation().
double scene2_SP2::endingTime private
Definition at line 267 of file scene2_SP2.h.
Referenced by Ending(), Init(), renderDeadPool(), and Reset().
double scene2_SP2::framePerSecond private
Definition at line 249 of file scene2_SP2.h.
Referenced by Init(), Render(), and Update().
Light scene2_SP2::light[2] private
Definition at line 231 of file scene2_SP2.h.
Referenced by Init(), and Render().
float scene2_SP2::LSPEED = 10.f private
Definition at line 182 of file scene2_SP2.h.
unsigned scene2_SP2::m_parameters[U_TOTAL] private
Definition at line 229 of file scene2_SP2.h.
Referenced by Init(), Render(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned scene2_SP2::m_programID private
Definition at line 228 of file scene2_SP2.h.
Referenced by Exit(), and Init().
unsigned scene2_SP2::m_vertexArrayID private
Definition at line 225 of file scene2_SP2.h.
Referenced by Exit(), and Init().
Mesh* scene2_SP2::meshList[NUM_GEOMETRY] private
Definition at line 226 of file scene2_SP2.h.
Referenced by Init(), Render(), RenderArrow(), RenderAsteroid(), RenderBoxes(), renderDeadPool(), renderDialogueBox(), RenderDiamond(), renderEndingScreen(), RenderFlyingVehicle(), RenderLandingVehicle(), RenderNPC(), RenderNumpad(), RenderRobot(), RenderSatellite(), RenderSkybox(), RenderSpaceShuttle(), RenderVault(), and rollingCredits().
MS scene2_SP2::modelStack private
Definition at line 240 of file scene2_SP2.h.
Referenced by Render(), RenderArrow(), RenderAsteroid(), RenderBoxes(), renderDeadPool(), RenderDiamond(), renderEndingScreen(), RenderFlyingVehicle(), RenderImageOnScreen(), RenderLandingVehicle(), renderMesh(), RenderNPC(), RenderNumpad(), RenderNumPadOnScreen(), RenderRobot(), RenderSatellite(), RenderSkybox(), RenderSpaceShuttle(), RenderText(), RenderTextOnScreen(), RenderUserInterface(), and RenderVault().
float scene2_SP2::moveToDeadPoolZ private
Definition at line 268 of file scene2_SP2.h.
Referenced by Ending(), Init(), Render(), and Reset().
bool scene2_SP2::NPCrotate private
Definition at line 171 of file scene2_SP2.h.
Referenced by Init(), and NPCAnimation().
bool scene2_SP2::NPCrotate2 private
Definition at line 172 of file scene2_SP2.h.
Referenced by Init(), and NPCAnimation().
bool scene2_SP2::NPCrotate3 private
Definition at line 173 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), and Reset().
float scene2_SP2::NPCrotating private
Definition at line 191 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), and RenderNPC().
float scene2_SP2::NPCrotating2 private
Definition at line 192 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), and RenderNPC().
float scene2_SP2::NPCrotating3 private
Definition at line 193 of file scene2_SP2.h.
Referenced by Init(), NPCAnimation(), RenderNPC(), and Reset().
NumPad scene2_SP2::Numpad private
Definition at line 233 of file scene2_SP2.h.
Referenced by Init(), Render(), RenderNumpad(), RenderVault(), Reset(), Update(), and VaultAnimation().
bool scene2_SP2::on_light private
Definition at line 162 of file scene2_SP2.h.
Referenced by Init(), and Render().
double scene2_SP2::PreventSpammingInstruction private
Definition at line 286 of file scene2_SP2.h.
Referenced by Init(), and Update().
MS scene2_SP2::projectionStack private
Definition at line 240 of file scene2_SP2.h.
Referenced by Init(), RenderImageOnScreen(), renderMesh(), RenderNumPadOnScreen(), RenderText(), RenderTextOnScreen(), and RenderUserInterface().
NPC scene2_SP2::robotNPC1 private
Definition at line 234 of file scene2_SP2.h.
Referenced by Init(), RenderNPC(), and Update().
NPC scene2_SP2::robotNPC2 private
Definition at line 235 of file scene2_SP2.h.
Referenced by BoxesAnimation(), Init(), NPCAnimation(), RenderNPC(), and Update().
NPC scene2_SP2::robotNPC3 private
Definition at line 236 of file scene2_SP2.h.
Referenced by Init(), RenderNPC(), and Update().
rot_civ scene2_SP2::Rot_Civ_ private
Definition at line 253 of file scene2_SP2.h.
Referenced by Init(), RenderRobot(), and Update().
bool scene2_SP2::satelliterotate private
Definition at line 166 of file scene2_SP2.h.
Referenced by Init(), and SatelliteAnimation().
float scene2_SP2::satelliterotating private
Definition at line 186 of file scene2_SP2.h.
Referenced by Init(), RenderSatellite(), and SatelliteAnimation().
float scene2_SP2::screenHeight private
Definition at line 250 of file scene2_SP2.h.
Referenced by Init().
float scene2_SP2::screenWidth private
Definition at line 250 of file scene2_SP2.h.
Referenced by Init().
float scene2_SP2::sizeofEndingScreen private
Definition at line 269 of file scene2_SP2.h.
Referenced by Ending(), Init(), renderEndingScreen(), and Reset().
bool scene2_SP2::smalldiamondrotate private
Definition at line 170 of file scene2_SP2.h.
Referenced by Init().
float scene2_SP2::smalldiamondrotating private
Definition at line 190 of file scene2_SP2.h.
Referenced by diamondAnimation(), Init(), and RenderDiamond().
bool scene2_SP2::smalldiamondtranslate private
Definition at line 169 of file scene2_SP2.h.
Referenced by diamondAnimation(), and Init().
float scene2_SP2::smalldiamondtranslating private
Definition at line 189 of file scene2_SP2.h.
Referenced by diamondAnimation(), Init(), and RenderDiamond().
bool scene2_SP2::stickpush private
Definition at line 164 of file scene2_SP2.h.
Referenced by Init(), Reset(), and VaultAnimation().
float scene2_SP2::stickpushing private
Definition at line 184 of file scene2_SP2.h.
Referenced by Init(), RenderVault(), Reset(), and VaultAnimation().
double scene2_SP2::update3DPos private
Definition at line 279 of file scene2_SP2.h.
Referenced by Init(), and Update().
NPC scene2_SP2::vault private
Definition at line 237 of file scene2_SP2.h.
Referenced by Init(), RenderVault(), and Update().
MS scene2_SP2::viewStack private
Definition at line 240 of file scene2_SP2.h.
Referenced by Render(), RenderImageOnScreen(), renderMesh(), RenderNumPadOnScreen(), RenderText(), RenderTextOnScreen(), and RenderUserInterface().
bool scene2_SP2::wheelturn private
Definition at line 163 of file scene2_SP2.h.
Referenced by Init(), and Reset().
float scene2_SP2::wheelturning private
Definition at line 183 of file scene2_SP2.h.
Referenced by Init(), RenderVault(), Reset(), and VaultAnimation().
The documentation for this class was generated from the following files:
MyGraphics/Source/scene2_SP2.h
MyGraphics/Source/scene2_SP2.cpp