My Application: scene3_SP2 Class Reference
scene3_SP2 Class Reference
inheirited from Scene and made improvised to it. To turn it into a game. This is the Scenario 3.
#include <scene3_SP2.h>
Public Member Functions
scene3_SP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
~scene3_SP2 ()
destructor
virtual void Init ()
initializing whatever is needed for the scene
virtual void Update (double dt)
where the logic of the game is, and update
virtual void Render ()
where the rendering of all the stuff we needed will be here
virtual void Exit ()
cleans up the scene
void reset ()
a method to reset everything inside scenario 2
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_LIGHTBALL, GEO_COMIC_TEXT, GEO_SPACE_SKYBOX,
GEO_FLYINGVEHICLE, GEO_LIGHT_WRAP, GEO_LIGHT_END, GEO_ASTEROID,
GEO_TEXT_BOX, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
rendering of the meshes
void RenderText (Mesh *mesh, std::string text, Color color)
rendering of the texts using quads
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
rendering of the texts using quads on screen
void RenderImageOnScreen (Mesh *mesh, float size, float x, float y)
rendering of image using quad on screen
void RenderImageOnScreen (Mesh *mesh, float x, float y, float sizeX, float sizeY)
a method to render the image on screen which offers non-uniform scalling
void RenderSkybox ()
a method to render the skybox
void renderSpaceShip ()
a method to render the space Ship
void animateSpaceShip (double dt)
a method to animate the spaceship and it's logic
void renderWarp ()
a method to render the warp
void animateWarp (double dt)
a method to animate the warp and it's logic
void initQuickTimeEvent (const char *fileLocation)
A Data Driven method that will initialised and determin what are the key press needed to pass this stage
void activateQTE (double &dt)
a method to update the logic of QTE
void renderQTE ()
a method to render QTE's stuff
void renderMeteorite ()
void renderInstructions ()
a method to render the instructions needed for QTE
void updateIntructions (double &dt)
a method to update the logic behind rendering of the instruction and prevent the text from going to fast
void renderDialogueBox (const string &name, const string &dialogue)
a method to render the dialogue box in a much simpler way
Private Attributes
bool on_light
Light light [2]
float LSPEED = 10.f
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
double framePerSecond
float screenWidth
float screenHeight
float jitteringShipY
bool toggleUp
float scaleShipZ
bool warppingOn
float scaleSkyBoxZ_
float warp_lightZ
double wait_on_white_screen
bool start_white_screen
float scaleLightEnd
bool turn_on_2nd
queue< char > quickTimeEvent
queue< char > DefaultquickTimeEvent
bool quickTimeEventFlag
double quickTimer
double makingSureNoDoubleTap
float moveAsteroidZ
float moveShipX
float moveShipZ
bool moveBack
bool quickTimeEventOver
bool youLost
bool instructionIsOver
vector< string > intructions
short order_of_text_
float rotationShipY
Detailed Description
inheirited from Scene and made improvised to it. To turn it into a game. This is the Scenario 3.
Class scene3_SP2:
Definition at line 32 of file scene3_SP2.h.
Member Enumeration Documentation
enum scene3_SP2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LIGHTBALL
GEO_COMIC_TEXT
GEO_SPACE_SKYBOX
GEO_FLYINGVEHICLE
GEO_LIGHT_WRAP
GEO_LIGHT_END
GEO_ASTEROID
GEO_TEXT_BOX
NUM_GEOMETRY
Definition at line 34 of file scene3_SP2.h.
enum scene3_SP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 50 of file scene3_SP2.h.
Constructor & Destructor Documentation
scene3_SP2::scene3_SP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
Parameters
screenwidth - width of the screen
screenheight - height of the screen
Definition at line 28 of file scene3_SP2.cpp.
scene3_SP2::~scene3_SP2 ()
destructor
Definition at line 37 of file scene3_SP2.cpp.
Member Function Documentation
void scene3_SP2::activateQTE (double & dt) private
a method to update the logic of QTE
Parameters
dt - frame time
Definition at line 957 of file scene3_SP2.cpp.
References quickTimeEventFlag, quickTimer, and youLost.
Referenced by Update().
void scene3_SP2::animateSpaceShip (double dt) private
a method to animate the spaceship and it's logic
Parameters
dt - frame time
Definition at line 802 of file scene3_SP2.cpp.
References jitteringShipY, moveAsteroidZ, quickTimeEventFlag, quickTimeEventOver, scaleLightEnd, scaleShipZ, scaleSkyBoxZ_, start_white_screen, toggleUp, warp_lightZ, and warppingOn.
Referenced by Update().
void scene3_SP2::animateWarp (double dt) private
a method to animate the warp and it's logic
Parameters
dt - frame time
Definition at line 912 of file scene3_SP2.cpp.
References Application::musics, BGMDriven::playWarpBackground(), scaleShipZ, warp_lightZ, and warppingOn.
Referenced by Update().
void scene3_SP2::Exit () virtual
cleans up the scene
Implements Scene.
Definition at line 632 of file scene3_SP2.cpp.
References m_programID, and m_vertexArrayID.
void scene3_SP2::Init () virtual
initializing whatever is needed for the scene
Implements Scene.
Definition at line 46 of file scene3_SP2.cpp.
References camera, Camera3::camType, Light::color, Light::cosCutoff, Light::cosInner, Camera3::cursorCoordX, Camera3::cursorCoordY, DefaultquickTimeEvent, Math::DegreeToRadian(), Light::exponent, Camera3::FIRST_PERSON, framePerSecond, MeshBuilder::GenerateAxes(), MaterialBuilder::GenerateBlinn(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ASTEROID, GEO_AXES, GEO_COMIC_TEXT, GEO_FLYINGVEHICLE, GEO_LIGHT_END, GEO_LIGHT_WRAP, GEO_LIGHTBALL, GEO_SPACE_SKYBOX, GEO_TEXT_BOX, Camera3::Init(), Camera3::InitObjects(), initQuickTimeEvent(), instructionIsOver, intructions, jitteringShipY, Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, makingSureNoDoubleTap, Mesh::material, meshList, moveAsteroidZ, moveBack, moveShipX, moveShipZ, on_light, order_of_text_, Light::position, Light::power, projectionStack, quickTimeEvent, quickTimeEventFlag, quickTimeEventOver, quickTimer, rotationShipY, scaleLightEnd, scaleShipZ, scaleSkyBoxZ_, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Mtx44::SetToPerspective(), Light::spotDirection, start_white_screen, Camera3::storage_of_objects, Mesh::textureID, toggleUp, turn_on_2nd, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, wait_on_white_screen, warp_lightZ, warppingOn, and youLost.
void scene3_SP2::initQuickTimeEvent (const char * fileLocation) private
A Data Driven method that will initialised and determin what are the key press needed to pass this stage
Parameters
fileLocation - the path name to the text file's location
Definition at line 930 of file scene3_SP2.cpp.
References quickTimeEvent.
Referenced by Init().
void scene3_SP2::Render () virtual
where the rendering of all the stuff we needed will be here
Implements Scene.
Definition at line 485 of file scene3_SP2.cpp.
References camera, framePerSecond, GEO_ASTEROID, GEO_COMIC_TEXT, GEO_LIGHT_END, GEO_LIGHTBALL, Camera3::getCameraXcoord(), Camera3::getCameraYcoord(), Camera3::getCameraZcoord(), instructionIsOver, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, moveAsteroidZ, on_light, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), quickTimeEventFlag, quickTimeEventOver, RenderImageOnScreen(), renderInstructions(), renderMesh(), renderQTE(), RenderSkybox(), renderSpaceShip(), RenderTextOnScreen(), renderWarp(), MS::Scale(), scaleLightEnd, scaleSkyBoxZ_, Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Light::spotDirection, start_white_screen, Camera3::storage_of_objects, Camera::target, MS::Top(), MS::Translate(), turn_on_2nd, U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, Camera::up, viewStack, warppingOn, Position::x, Vector3::x, Position::y, Vector3::y, youLost, Position::z, and Vector3::z.
void scene3_SP2::renderDialogueBox (const string & name, const string & dialogue) private
a method to render the dialogue box in a much simpler way
Parameters
name - the name of the interacted object
dialogue - what will be said by that object
Definition at line 1061 of file scene3_SP2.cpp.
References GEO_COMIC_TEXT, GEO_TEXT_BOX, meshList, RenderImageOnScreen(), and RenderTextOnScreen().
Referenced by renderInstructions(), and renderQTE().
void scene3_SP2::RenderImageOnScreen (Mesh * mesh, float size, float x, float y) private
rendering of image using quad on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 741 of file scene3_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render(), and renderDialogueBox().
void scene3_SP2::RenderImageOnScreen (Mesh * mesh, float x, float y, float sizeX, float sizeY) private
a method to render the image on screen which offers non-uniform scalling
Parameters
mesh - the Shape that will be rendered
x - the x coordinate of the image
y - the y coordinate of the image
sizeX - the scalling of image based on X-axis
sizeY - the scalling of image based on Y-axis
Definition at line 1084 of file scene3_SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
void scene3_SP2::renderInstructions () private
a method to render the instructions needed for QTE
Definition at line 1028 of file scene3_SP2.cpp.
References intructions, order_of_text_, and renderDialogueBox().
Referenced by Render().
void scene3_SP2::renderMesh (Mesh * mesh, bool enableLight) private
rendering of the meshes
Parameters
mesh - the specific mesh
enableLight - to enable lighting on the object
Definition at line 437 of file scene3_SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderImageOnScreen(), RenderSkybox(), renderSpaceShip(), and renderWarp().
void scene3_SP2::renderMeteorite () private
void scene3_SP2::renderQTE () private
a method to render QTE's stuff
Definition at line 971 of file scene3_SP2.cpp.
References GEO_COMIC_TEXT, meshList, quickTimeEvent, quickTimeEventFlag, quickTimer, renderDialogueBox(), and RenderTextOnScreen().
Referenced by Render().
void scene3_SP2::RenderSkybox () private
a method to render the skybox
Definition at line 769 of file scene3_SP2.cpp.
References GEO_SPACE_SKYBOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), and renderMesh().
Referenced by Render().
void scene3_SP2::renderSpaceShip () private
a method to render the space Ship
Definition at line 781 of file scene3_SP2.cpp.
References camera, GEO_FLYINGVEHICLE, jitteringShipY, meshList, modelStack, moveShipX, moveShipZ, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), rotationShipY, MS::Scale(), scaleShipZ, Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void scene3_SP2::RenderText (Mesh * mesh, std::string text, Color color) private
rendering of the texts using quads
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
Definition at line 648 of file scene3_SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void scene3_SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
rendering of the texts using quads on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 688 of file scene3_SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), renderDialogueBox(), and renderQTE().
void scene3_SP2::renderWarp () private
a method to render the warp
Definition at line 859 of file scene3_SP2.cpp.
References camera, GEO_LIGHT_WRAP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), quickTimeEventFlag, renderMesh(), MS::Scale(), Camera3::storage_of_objects, MS::Translate(), and warp_lightZ.
Referenced by Render().
void scene3_SP2::reset ()
a method to reset everything inside scenario 2
Definition at line 988 of file scene3_SP2.cpp.
References camera, DefaultquickTimeEvent, jitteringShipY, makingSureNoDoubleTap, moveAsteroidZ, moveBack, moveShipX, moveShipZ, quickTimeEvent, quickTimeEventFlag, quickTimeEventOver, quickTimer, Camera3::Reset(), rotationShipY, scaleLightEnd, scaleShipZ, scaleSkyBoxZ_, start_white_screen, toggleUp, wait_on_white_screen, warp_lightZ, warppingOn, and youLost.
Referenced by Update().
void scene3_SP2::Update (double dt) virtual
where the logic of the game is, and update
Parameters
dt - time frame
Implements Scene.
Definition at line 279 of file scene3_SP2.cpp.
References activateQTE(), animateSpaceShip(), animateWarp(), camera, Application::changeIntoScenario1(), Application::changeIntoScenario3(), Vector3::Cross(), Camera3::defaultPosition, Camera3::defaultUp, Math::DegreeToRadian(), framePerSecond, Camera3::getCameraXrotation(), Camera3::getCameraYrotation(), instructionIsOver, Application::IsKeyPressed(), makingSureNoDoubleTap, moveAsteroidZ, moveBack, moveShipX, moveShipZ, Application::musics, order_of_text_, BGMDriven::playPokemonBattleBackground(), Camera::position, quickTimeEvent, quickTimeEventFlag, quickTimeEventOver, reset(), rotationShipY, start_white_screen, Camera::target, Camera::up, updateIntructions(), wait_on_white_screen, warppingOn, Vector3::x, Vector3::y, youLost, and Vector3::z.
void scene3_SP2::updateIntructions (double & dt) private
a method to update the logic behind rendering of the instruction and prevent the text from going to fast
Parameters
dt - frame time
Definition at line 1040 of file scene3_SP2.cpp.
References instructionIsOver, intructions, Application::IsKeyPressed(), makingSureNoDoubleTap, and order_of_text_.
Referenced by Update().
Field Documentation
Camera3 scene3_SP2::camera private
Definition at line 115 of file scene3_SP2.h.
Referenced by Init(), Render(), renderSpaceShip(), renderWarp(), reset(), and Update().
queue<char> scene3_SP2::DefaultquickTimeEvent private
Definition at line 160 of file scene3_SP2.h.
Referenced by Init(), and reset().
double scene3_SP2::framePerSecond private
Definition at line 124 of file scene3_SP2.h.
Referenced by Init(), Render(), and Update().
bool scene3_SP2::instructionIsOver private
Definition at line 178 of file scene3_SP2.h.
Referenced by Init(), Render(), Update(), and updateIntructions().
vector<string> scene3_SP2::intructions private
Definition at line 179 of file scene3_SP2.h.
Referenced by Init(), renderInstructions(), and updateIntructions().
float scene3_SP2::jitteringShipY private
Definition at line 132 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), renderSpaceShip(), and reset().
Light scene3_SP2::light[2] private
Definition at line 106 of file scene3_SP2.h.
Referenced by Init(), and Render().
float scene3_SP2::LSPEED = 10.f private
Definition at line 107 of file scene3_SP2.h.
unsigned scene3_SP2::m_parameters[U_TOTAL] private
Definition at line 113 of file scene3_SP2.h.
Referenced by Init(), Render(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned scene3_SP2::m_programID private
Definition at line 112 of file scene3_SP2.h.
Referenced by Exit(), and Init().
unsigned scene3_SP2::m_vertexArrayID private
Definition at line 109 of file scene3_SP2.h.
Referenced by Exit(), and Init().
double scene3_SP2::makingSureNoDoubleTap private
Definition at line 166 of file scene3_SP2.h.
Referenced by Init(), reset(), Update(), and updateIntructions().
Mesh* scene3_SP2::meshList[NUM_GEOMETRY] private
Definition at line 110 of file scene3_SP2.h.
Referenced by Init(), Render(), renderDialogueBox(), renderQTE(), RenderSkybox(), renderSpaceShip(), and renderWarp().
MS scene3_SP2::modelStack private
Definition at line 117 of file scene3_SP2.h.
Referenced by Render(), RenderImageOnScreen(), renderMesh(), RenderSkybox(), renderSpaceShip(), RenderText(), RenderTextOnScreen(), and renderWarp().
float scene3_SP2::moveAsteroidZ private
Definition at line 168 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), Render(), reset(), and Update().
bool scene3_SP2::moveBack private
Definition at line 170 of file scene3_SP2.h.
Referenced by Init(), reset(), and Update().
float scene3_SP2::moveShipX private
Definition at line 169 of file scene3_SP2.h.
Referenced by Init(), renderSpaceShip(), reset(), and Update().
float scene3_SP2::moveShipZ private
Definition at line 169 of file scene3_SP2.h.
Referenced by Init(), renderSpaceShip(), reset(), and Update().
bool scene3_SP2::on_light private
Definition at line 105 of file scene3_SP2.h.
Referenced by Init(), and Render().
short scene3_SP2::order_of_text_ private
Definition at line 180 of file scene3_SP2.h.
Referenced by Init(), renderInstructions(), Update(), and updateIntructions().
MS scene3_SP2::projectionStack private
Definition at line 117 of file scene3_SP2.h.
Referenced by Init(), RenderImageOnScreen(), renderMesh(), RenderText(), and RenderTextOnScreen().
queue<char> scene3_SP2::quickTimeEvent private
Definition at line 159 of file scene3_SP2.h.
Referenced by Init(), initQuickTimeEvent(), renderQTE(), reset(), and Update().
bool scene3_SP2::quickTimeEventFlag private
Definition at line 162 of file scene3_SP2.h.
Referenced by activateQTE(), animateSpaceShip(), Init(), Render(), renderQTE(), renderWarp(), reset(), and Update().
bool scene3_SP2::quickTimeEventOver private
Definition at line 171 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), Render(), reset(), and Update().
double scene3_SP2::quickTimer private
Definition at line 165 of file scene3_SP2.h.
Referenced by activateQTE(), Init(), renderQTE(), and reset().
float scene3_SP2::rotationShipY private
Definition at line 185 of file scene3_SP2.h.
Referenced by Init(), renderSpaceShip(), reset(), and Update().
float scene3_SP2::scaleLightEnd private
Definition at line 151 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), Render(), and reset().
float scene3_SP2::scaleShipZ private
Definition at line 134 of file scene3_SP2.h.
Referenced by animateSpaceShip(), animateWarp(), Init(), renderSpaceShip(), and reset().
float scene3_SP2::scaleSkyBoxZ_ private
Definition at line 139 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), Render(), and reset().
float scene3_SP2::screenHeight private
Definition at line 125 of file scene3_SP2.h.
Referenced by Init().
float scene3_SP2::screenWidth private
Definition at line 125 of file scene3_SP2.h.
Referenced by Init().
bool scene3_SP2::start_white_screen private
Definition at line 150 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), Render(), reset(), and Update().
bool scene3_SP2::toggleUp private
Definition at line 133 of file scene3_SP2.h.
Referenced by animateSpaceShip(), Init(), and reset().
bool scene3_SP2::turn_on_2nd private
Definition at line 155 of file scene3_SP2.h.
Referenced by Init(), and Render().
MS scene3_SP2::viewStack private
Definition at line 117 of file scene3_SP2.h.
Referenced by Render(), RenderImageOnScreen(), renderMesh(), RenderText(), and RenderTextOnScreen().
double scene3_SP2::wait_on_white_screen private
Definition at line 149 of file scene3_SP2.h.
Referenced by Init(), reset(), and Update().
float scene3_SP2::warp_lightZ private
Definition at line 148 of file scene3_SP2.h.
Referenced by animateSpaceShip(), animateWarp(), Init(), renderWarp(), and reset().
bool scene3_SP2::warppingOn private
Definition at line 135 of file scene3_SP2.h.
Referenced by animateSpaceShip(), animateWarp(), Init(), Render(), reset(), and Update().
bool scene3_SP2::youLost private
Definition at line 172 of file scene3_SP2.h.
Referenced by activateQTE(), Init(), Render(), reset(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/scene3_SP2.h
MyGraphics/Source/scene3_SP2.cpp