My Application: minigame Class Reference
minigame Class Reference
#include <scene2_minigame.h>
Public Member Functions
minigame ()
Default Constructor
~minigame ()
Destructor
void init ()
initialised and randomises values for all the pieces' rotation and initialise other variables
float piece1 ()
get minigame piece 1's rotation
float piece2 ()
get minigame piece 2's rotation
float piece3 ()
get minigame piece 3's rotation
float piece4 ()
get minigame piece 4's rotation
float piece5 ()
get minigame piece 5's rotation
float piece6 ()
get minigame piece 6's rotation
float piece7 ()
get minigame piece 7's rotation
float piece8 ()
get minigame piece 8's rotation
float piece9 ()
get minigame piece 9's rotation
void selection_pointer ()
to calculate which piece the minigame's selection pointer points to
void changePieceRotation ()
detect when the player rotates a pice
void update (double dt, bool start_game)
update the minigame's progress
bool result ()
check if minigame is completed
void updatePieceState ()
update rotation for al the pieces
void minigame_started (bool started)
bool minigame_started ()
get status for minigame if it has started or not
short get_selector_state ()
get where the selector is pointing to
Private Attributes
short piece_state
float piece1_rotate
float piece2_rotate
float piece3_rotate
float piece4_rotate
float piece5_rotate
float piece6_rotate
float piece7_rotate
float piece8_rotate
float piece9_rotate
short piece1_state
short piece2_state
short piece3_state
short piece4_state
short piece5_state
short piece6_state
short piece7_state
short piece8_state
short piece9_state
bool start
double time
double input_delay
Detailed Description
Definition at line 14 of file scene2_minigame.h.
Constructor & Destructor Documentation
minigame::minigame ()
Default Constructor
Definition at line 10 of file scene2_minigame.cpp.
minigame::~minigame ()
Destructor
Definition at line 20 of file scene2_minigame.cpp.
Member Function Documentation
void minigame::changePieceRotation ()
detect when the player rotates a pice
Definition at line 220 of file scene2_minigame.cpp.
References input_delay, Application::IsKeyPressed(), piece1_state, piece2_state, piece3_state, piece4_state, piece5_state, piece6_state, piece7_state, piece8_state, piece9_state, piece_state, and time.
Referenced by update().
short minigame::get_selector_state ()
get where the selector is pointing to
Returns
- which piece the selector should be pointing at
Definition at line 377 of file scene2_minigame.cpp.
References piece_state.
Referenced by sceneSP2::RenderMinigamePieces().
void minigame::init ()
initialised and randomises values for all the pieces' rotation and initialise other variables
Definition at line 30 of file scene2_minigame.cpp.
References input_delay, piece1_rotate, piece1_state, piece2_rotate, piece2_state, piece3_rotate, piece3_state, piece4_rotate, piece4_state, piece5_rotate, piece5_state, piece6_rotate, piece6_state, piece7_rotate, piece7_state, piece8_rotate, piece8_state, piece9_rotate, piece9_state, piece_state, Math::RandIntMinMax(), start, and time.
Referenced by sceneSP2::Init(), and sceneSP2::reset().
void minigame::minigame_started (bool started)
Referenced by sceneSP2::RenderMinigamePieces(), and sceneSP2::Update().
bool minigame::minigame_started ()
get status for minigame if it has started or not
Returns
true - minigame has started
false - minigame has not started
Definition at line 365 of file scene2_minigame.cpp.
References start.
float minigame::piece1 ()
get minigame piece 1's rotation
Returns
- amount of rotation for piece 1
Definition at line 65 of file scene2_minigame.cpp.
References piece1_rotate, and piece1_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece2 ()
get minigame piece 2's rotation
Returns
- amount of rotation for piece 2
Definition at line 76 of file scene2_minigame.cpp.
References piece2_rotate, and piece2_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece3 ()
get minigame piece 3's rotation
Returns
- amount of rotation for piece 3
Definition at line 87 of file scene2_minigame.cpp.
References piece3_rotate, and piece3_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece4 ()
get minigame piece 4's rotation
Returns
- amount of rotation for piece 4
Definition at line 98 of file scene2_minigame.cpp.
References piece4_rotate, and piece4_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece5 ()
get minigame piece 5's rotation
Returns
- amount of rotation for piece 5
Definition at line 109 of file scene2_minigame.cpp.
References piece5_rotate, and piece5_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece6 ()
get minigame piece 6's rotation
Returns
- amount of rotation for piece 6
Definition at line 120 of file scene2_minigame.cpp.
References piece6_rotate, and piece6_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece7 ()
get minigame piece 7's rotation
Returns
- amount of rotation for piece 7
Definition at line 131 of file scene2_minigame.cpp.
References piece7_rotate, and piece7_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece8 ()
get minigame piece 8's rotation
Returns
- amount of rotation for piece 8
Definition at line 142 of file scene2_minigame.cpp.
References piece8_rotate, and piece8_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
float minigame::piece9 ()
get minigame piece 9's rotation
Returns
- amount of rotation for piece 9
Definition at line 153 of file scene2_minigame.cpp.
References piece9_rotate, and piece9_state.
Referenced by sceneSP2::RenderMinigamePieces(), and updatePieceState().
bool minigame::result ()
check if minigame is completed
Returns
true - player has completed minigame
false - player has not completed minigame
Definition at line 316 of file scene2_minigame.cpp.
References piece1_state, piece2_state, piece3_state, piece4_state, piece5_state, piece6_state, piece7_state, piece8_state, and piece9_state.
Referenced by sceneSP2::RenderMinigamePieces(), update(), and sceneSP2::Update().
void minigame::selection_pointer ()
to calculate which piece the minigame's selection pointer points to
Definition at line 181 of file scene2_minigame.cpp.
References input_delay, Application::IsKeyPressed(), piece_state, and time.
Referenced by update().
void minigame::update (double dt, bool start_game)
update the minigame's progress
Parameters
dt - delta time
start_game - boolean to check if player has started minigame
Definition at line 343 of file scene2_minigame.cpp.
References changePieceRotation(), result(), selection_pointer(), start, time, and updatePieceState().
Referenced by sceneSP2::Update().
void minigame::updatePieceState ()
update rotation for al the pieces
Definition at line 163 of file scene2_minigame.cpp.
References piece1(), piece2(), piece3(), piece4(), piece5(), piece6(), piece7(), piece8(), and piece9().
Referenced by update().
Field Documentation
double minigame::input_delay private
Definition at line 59 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), and selection_pointer().
float minigame::piece1_rotate private
Definition at line 39 of file scene2_minigame.h.
Referenced by init(), and piece1().
short minigame::piece1_state private
Definition at line 48 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece1(), and result().
float minigame::piece2_rotate private
Definition at line 40 of file scene2_minigame.h.
Referenced by init(), and piece2().
short minigame::piece2_state private
Definition at line 49 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece2(), and result().
float minigame::piece3_rotate private
Definition at line 41 of file scene2_minigame.h.
Referenced by init(), and piece3().
short minigame::piece3_state private
Definition at line 50 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece3(), and result().
float minigame::piece4_rotate private
Definition at line 42 of file scene2_minigame.h.
Referenced by init(), and piece4().
short minigame::piece4_state private
Definition at line 51 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece4(), and result().
float minigame::piece5_rotate private
Definition at line 43 of file scene2_minigame.h.
Referenced by init(), and piece5().
short minigame::piece5_state private
Definition at line 52 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece5(), and result().
float minigame::piece6_rotate private
Definition at line 44 of file scene2_minigame.h.
Referenced by init(), and piece6().
short minigame::piece6_state private
Definition at line 53 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece6(), and result().
float minigame::piece7_rotate private
Definition at line 45 of file scene2_minigame.h.
Referenced by init(), and piece7().
short minigame::piece7_state private
Definition at line 54 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece7(), and result().
float minigame::piece8_rotate private
Definition at line 46 of file scene2_minigame.h.
Referenced by init(), and piece8().
short minigame::piece8_state private
Definition at line 55 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece8(), and result().
float minigame::piece9_rotate private
Definition at line 47 of file scene2_minigame.h.
Referenced by init(), and piece9().
short minigame::piece9_state private
Definition at line 56 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), piece9(), and result().
short minigame::piece_state private
Definition at line 38 of file scene2_minigame.h.
Referenced by changePieceRotation(), get_selector_state(), init(), and selection_pointer().
bool minigame::start private
Definition at line 57 of file scene2_minigame.h.
Referenced by init(), minigame_started(), and update().
double minigame::time private
Definition at line 58 of file scene2_minigame.h.
Referenced by changePieceRotation(), init(), selection_pointer(), and update().
The documentation for this class was generated from the following files:
MyGraphics/Source/scene2_minigame.h
MyGraphics/Source/scene2_minigame.cpp