My Application: NumPad Class Reference
NumPad Class Reference
inheirited from GameObject
#include <NumPad.h>
Public Member Functions
NumPad ()
Constructor.
~NumPad ()
Destrucotr.
void Init (Camera3 &cameraDub, const Vector3 &origPos)
initializing the thing needed for the scene
void Update (double dt)
updating the numpad interaction
void NumpadProgram (double dt)
Numpad interaction.
void Reset ()
Reset all animations & values to default.
bool NumpadVerify ()
To check the player's input with the correct password.
bool interactiontext ()
"Press 'C' to interact" will appear if player's position is inside interaction area
bool interaction ()
Check whether player's position is inside interaction area.
bool displayerror ()
Display text "Try Again!" if the input does not match with the correct password.
bool NumpadRenderOnScreen ()
Check whether player's position is inside interaction area and 'C' button is pressed to open numpad on screen.
float getfirstrotate ()
First digit rotate.
float getsecondrotate ()
Second digit rotate.
float getthirdrotate ()
Third digit rotate.
float getfourthrotate ()
Fourth digit rotate.
float getarrowposition ()
Get arrow position.
int getdigit1 ()
Get the first digit.
int getdigit2 ()
Get the second digit.
int getdigit3 ()
Get the third digit.
int getdigit4 ()
Get the fourth digit.
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Private Attributes
bool check
bool open
bool close
bool render
float firstrotate
float secondrotate
float thirdrotate
float fourthrotate
float time_delay
float changearrow
float arrow
int digit1
int digit2
int digit3
int digit4
int hahaha
double time
Camera3 * camera
Vector3 pos
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Protected Attributes inherited from GameObject
string Name_
Detailed Description
inheirited from GameObject
Class NumPad:
Definition at line 28 of file NumPad.h.
Constructor & Destructor Documentation
NumPad::NumPad ()
Constructor.
Definition at line 15 of file NumPad.cpp.
NumPad::~NumPad ()
Destrucotr.
Definition at line 25 of file NumPad.cpp.
Member Function Documentation
bool NumPad::displayerror ()
Display text "Try Again!" if the input does not match with the correct password.
Returns
Return true if input does not match with the correct password, else return false;
Definition at line 332 of file NumPad.cpp.
References check, interaction(), and NumpadVerify().
Referenced by scene2_SP2::Render().
float NumPad::getarrowposition ()
Get arrow position.
Returns
Return arrow position
Definition at line 443 of file NumPad.cpp.
References changearrow.
Referenced by scene2_SP2::Render().
int NumPad::getdigit1 ()
Get the first digit.
Returns
Return first digit value
Definition at line 458 of file NumPad.cpp.
References digit1.
int NumPad::getdigit2 ()
Get the second digit.
Returns
Return second digit value
Definition at line 473 of file NumPad.cpp.
References digit2.
int NumPad::getdigit3 ()
Get the third digit.
Returns
Return third digit value
Definition at line 488 of file NumPad.cpp.
References digit3.
int NumPad::getdigit4 ()
Get the fourth digit.
Returns
Return fourth digit value
Definition at line 503 of file NumPad.cpp.
References digit4.
float NumPad::getfirstrotate ()
First digit rotate.
Returns
Return firstrotate value
Definition at line 382 of file NumPad.cpp.
References firstrotate.
Referenced by scene2_SP2::Render(), and scene2_SP2::RenderNumpad().
float NumPad::getfourthrotate ()
Fourth digit rotate.
Returns
Return fourthrotate value
Definition at line 428 of file NumPad.cpp.
References fourthrotate.
Referenced by scene2_SP2::Render(), and scene2_SP2::RenderNumpad().
float NumPad::getsecondrotate ()
Second digit rotate.
Returns
Return secondrotate value
Definition at line 397 of file NumPad.cpp.
References secondrotate.
Referenced by scene2_SP2::Render(), and scene2_SP2::RenderNumpad().
float NumPad::getthirdrotate ()
Third digit rotate.
Returns
Return thirdrotate value
Definition at line 412 of file NumPad.cpp.
References thirdrotate.
Referenced by scene2_SP2::Render(), and scene2_SP2::RenderNumpad().
void NumPad::Init (Camera3 & cameraDub, const Vector3 & origPos)
initializing the thing needed for the scene
Parameters
&cameraDub - get the camera's position
&origPos - get the Numpad's position
Definition at line 39 of file NumPad.cpp.
References arrow, camera, changearrow, check, close, digit1, digit2, digit3, digit4, firstrotate, fourthrotate, open, pos, render, secondrotate, thirdrotate, time, and time_delay.
Referenced by scene2_SP2::Init().
bool NumPad::interaction ()
Check whether player's position is inside interaction area.
Returns
Return true if player's position is inside interaction area
Definition at line 359 of file NumPad.cpp.
References camera, Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), pos, Vector3::x, and Vector3::z.
Referenced by displayerror(), interactiontext(), NumpadProgram(), NumpadRenderOnScreen(), and Update().
bool NumPad::interactiontext ()
"Press 'C' to interact" will appear if player's position is inside interaction area
return Return true if the player inside interaction area, else false
Definition at line 132 of file NumPad.cpp.
References interaction().
Referenced by NumpadProgram(), scene2_SP2::Render(), and scene2_SP2::RenderVault().
void NumPad::NumpadProgram (double dt)
Numpad interaction.
Parameters
dt - time frame
Definition at line 171 of file NumPad.cpp.
References arrow, digit1, digit2, digit3, digit4, firstrotate, fourthrotate, interaction(), interactiontext(), Application::IsKeyPressed(), NumpadRenderOnScreen(), secondrotate, thirdrotate, time, and time_delay.
Referenced by scene2_SP2::Update().
bool NumPad::NumpadRenderOnScreen ()
Check whether player's position is inside interaction area and 'C' button is pressed to open numpad on screen.
return Return true if the player inside interaction area and 'C' button is pressed, else false
Definition at line 149 of file NumPad.cpp.
References interaction(), and open.
Referenced by NumpadProgram(), scene2_SP2::Render(), and scene2_SP2::Update().
bool NumPad::NumpadVerify ()
To check the player's input with the correct password.
Returns
Return true if the input match with the correct password, else return false
Definition at line 312 of file NumPad.cpp.
References check, digit1, digit2, digit3, and digit4.
Referenced by displayerror(), scene2_SP2::Update(), and scene2_SP2::VaultAnimation().
void NumPad::Reset ()
Reset all animations & values to default.
Definition at line 513 of file NumPad.cpp.
References arrow, changearrow, check, close, digit1, digit2, digit3, digit4, firstrotate, fourthrotate, open, render, secondrotate, thirdrotate, time, and time_delay.
Referenced by scene2_SP2::Reset().
void NumPad::Update (double dt)
updating the numpad interaction
Parameters
dt - time frame
Definition at line 59 of file NumPad.cpp.
References arrow, changearrow, check, interaction(), Application::IsKeyPressed(), open, time, and time_delay.
Referenced by scene2_SP2::Update().
Field Documentation
float NumPad::arrow private
Definition at line 69 of file NumPad.h.
Referenced by Init(), NumpadProgram(), Reset(), and Update().
Camera3* NumPad::camera private
Definition at line 79 of file NumPad.h.
Referenced by Init(), and interaction().
float NumPad::changearrow private
Definition at line 68 of file NumPad.h.
Referenced by getarrowposition(), Init(), Reset(), and Update().
bool NumPad::check private
Definition at line 58 of file NumPad.h.
Referenced by displayerror(), Init(), NumpadVerify(), Reset(), and Update().
bool NumPad::close private
Definition at line 60 of file NumPad.h.
Referenced by Init(), and Reset().
int NumPad::digit1 private
Definition at line 71 of file NumPad.h.
Referenced by getdigit1(), Init(), NumpadProgram(), NumpadVerify(), and Reset().
int NumPad::digit2 private
Definition at line 72 of file NumPad.h.
Referenced by getdigit2(), Init(), NumpadProgram(), NumpadVerify(), and Reset().
int NumPad::digit3 private
Definition at line 73 of file NumPad.h.
Referenced by getdigit3(), Init(), NumpadProgram(), NumpadVerify(), and Reset().
int NumPad::digit4 private
Definition at line 74 of file NumPad.h.
Referenced by getdigit4(), Init(), NumpadProgram(), NumpadVerify(), and Reset().
float NumPad::firstrotate private
Definition at line 63 of file NumPad.h.
Referenced by getfirstrotate(), Init(), NumpadProgram(), and Reset().
float NumPad::fourthrotate private
Definition at line 66 of file NumPad.h.
Referenced by getfourthrotate(), Init(), NumpadProgram(), and Reset().
int NumPad::hahaha private
Definition at line 75 of file NumPad.h.
bool NumPad::open private
Definition at line 59 of file NumPad.h.
Referenced by Init(), NumpadRenderOnScreen(), Reset(), and Update().
Vector3 NumPad::pos private
Definition at line 80 of file NumPad.h.
Referenced by Init(), and interaction().
bool NumPad::render private
Definition at line 61 of file NumPad.h.
Referenced by Init(), and Reset().
float NumPad::secondrotate private
Definition at line 64 of file NumPad.h.
Referenced by getsecondrotate(), Init(), NumpadProgram(), and Reset().
float NumPad::thirdrotate private
Definition at line 65 of file NumPad.h.
Referenced by getthirdrotate(), Init(), NumpadProgram(), and Reset().
double NumPad::time private
Definition at line 77 of file NumPad.h.
Referenced by Init(), NumpadProgram(), Reset(), and Update().
float NumPad::time_delay private
Definition at line 67 of file NumPad.h.
Referenced by Init(), NumpadProgram(), Reset(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/NumPad.h
MyGraphics/Source/NumPad.cpp