My Application: objectsForDisplay Class Reference
objectsForDisplay Class Reference
Inheirited from GameObject It has it's own text reader file to input it's values, position, and boundary.
#include <objectsForDisplay.h>
Public Member Functions
objectsForDisplay ()
Default Constructor
~objectsForDisplay ()
Destructor
void init (const char *fileLocation)
initialised it's values through text file reader
void init (Vector3 pos, float boundaryX, float boundaryZ, string name)
initialised it's variables by passing in parameter
bool boundaryCheck (const float &playerPosX, const float &playerPosZ)
the boundary check with the camera's position
float getObjectposX ()
get this object's X coordinate
float getObjectposY ()
get this object's Y coordinate
float getObjectposZ ()
get this object's Z coordinate
float getBoundaryRadiusX ()
get this object's X boundary range
float getBoundaryRadiusZ ()
get this object's Z boundary range
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Data Fields
Vector3 objectPos
Vector3 originalPos
Protected Attributes
float boundaryRadiusX
float boundaryRadiusZ
Protected Attributes inherited from GameObject
string Name_
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Detailed Description
Inheirited from GameObject It has it's own text reader file to input it's values, position, and boundary.
Class objectsForDisplay:
Definition at line 24 of file objectsForDisplay.h.
Constructor & Destructor Documentation
objectsForDisplay::objectsForDisplay ()
Default Constructor
Definition at line 16 of file objectsForDisplay.cpp.
objectsForDisplay::~objectsForDisplay ()
Destructor
Definition at line 27 of file objectsForDisplay.cpp.
Member Function Documentation
bool objectsForDisplay::boundaryCheck (const float & playerPosX, const float & playerPosZ)
the boundary check with the camera's position
Parameters
playerPosX - X coordinate of the camera
playerPosZ - Z coordinate of the camera
Returns
true - if the player is not within it's box boundary
false - if the player is within it's box boundary
Definition at line 113 of file objectsForDisplay.cpp.
References boundaryRadiusX, boundaryRadiusZ, objectPos, Vector3::x, and Vector3::z.
float objectsForDisplay::getBoundaryRadiusX ()
get this object's X boundary range
Returns
- X boundary range of the object
Definition at line 184 of file objectsForDisplay.cpp.
References boundaryRadiusX.
Referenced by SekHeng::interactingWithItem().
float objectsForDisplay::getBoundaryRadiusZ ()
get this object's Z boundary range
Returns
- Z boundary range of the object
Definition at line 195 of file objectsForDisplay.cpp.
References boundaryRadiusZ.
Referenced by SekHeng::interactingWithItem().
float objectsForDisplay::getObjectposX ()
get this object's X coordinate
Returns
- X coordinate of the object
Definition at line 131 of file objectsForDisplay.cpp.
References objectPos, and Vector3::x.
Referenced by SekHeng::interactingWithItem(), sceneSP2::renderingSekHeng(), and scene2_SP2::RenderRobot().
float objectsForDisplay::getObjectposY ()
get this object's Y coordinate
Returns
- Y coordinate of the object
Definition at line 142 of file objectsForDisplay.cpp.
References objectPos, and Vector3::y.
Referenced by sceneSP2::renderingSekHeng(), and scene2_SP2::RenderRobot().
float objectsForDisplay::getObjectposZ ()
get this object's Z coordinate
Returns
- Z coordinate of the object
Definition at line 153 of file objectsForDisplay.cpp.
References objectPos, and Vector3::z.
Referenced by SekHeng::interactingWithItem(), sceneSP2::renderingSekHeng(), and scene2_SP2::RenderRobot().
void objectsForDisplay::init (const char * fileLocation)
initialised it's values through text file reader
Parameters
fileLocation - the path name to the text file
Definition at line 38 of file objectsForDisplay.cpp.
References boundaryRadiusX, boundaryRadiusZ, GameObject::Name_, objectPos, originalPos, Vector3::x, Vector3::y, and Vector3::z.
Referenced by scene2_SP2::Init(), sceneSP2::Init(), Camera3::InitObjects(), SekHeng::reset(), and SekHeng::SekHeng().
void objectsForDisplay::init (Vector3 pos, float boundaryX, float boundaryZ, string name)
initialised it's variables by passing in parameter
Parameters
pos - Coordinates of the object
boundaryX - boundary of the object based on the X Axis
boundaryZ - boundary of the object based on the Z Axis
name - Name of the object
Definition at line 170 of file objectsForDisplay.cpp.
References boundaryRadiusX, boundaryRadiusZ, GameObject::Name_, and objectPos.
Field Documentation
float objectsForDisplay::boundaryRadiusX protected
Definition at line 43 of file objectsForDisplay.h.
Referenced by boundaryCheck(), getBoundaryRadiusX(), init(), rot_civ::interaction(), and SekHeng::interaction().
float objectsForDisplay::boundaryRadiusZ protected
Definition at line 43 of file objectsForDisplay.h.
Referenced by boundaryCheck(), getBoundaryRadiusZ(), init(), rot_civ::interaction(), and SekHeng::interaction().
Vector3 objectsForDisplay::objectPos
Definition at line 36 of file objectsForDisplay.h.
Referenced by boundaryCheck(), getObjectposX(), getObjectposY(), getObjectposZ(), init(), rot_civ::interaction(), SekHeng::interaction(), and SekHeng::reset().
Vector3 objectsForDisplay::originalPos
Definition at line 37 of file objectsForDisplay.h.
Referenced by init(), and SekHeng::reset().
The documentation for this class was generated from the following files:
MyGraphics/Source/objectsForDisplay.h
MyGraphics/Source/objectsForDisplay.cpp