My Application: sceneSP2 Class Reference
sceneSP2 Class Reference
inheirited from Scene and made improvised to it. To turn it into a game. This is Scenario 1
#include <sceneSP2.h>
Public Member Functions
sceneSP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
~sceneSP2 ()
destructor
virtual void Init ()
initializing whatever is needed for the scene
virtual void Update (double dt)
where the logic of the game is, and update
virtual void Render ()
where the rendering of all the stuff we needed will be here
virtual void Exit ()
cleans up the scene
void reset ()
reset the entire scene 1 /*
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_LIGHTBALL, GEO_COMIC_TEXT, GEO_LANDVEHICLE,
GEO_FLYINGVEHICLE, GEO_SPACE_SKYBOX, GEO_SPACE_GROUNDMESH, GEO_SPACE_WALL,
GEO_CRYOSTASIS, GEO_UI, GEO_SCREWDRIVER, GEO_CONTAINER,
GEO_GASOLINE, GEO_HAMMER, GEO_STATION, GEO_CHAIR,
GEO_TABLE, GEO_BOX, GEO_DOOR, GEO_KEYCARD,
GEO_TELEPORTER, GEO_PARTICLE_LIGHT, GEO_PARTICLE_CUBE, GEO_BUILDINGRED,
GEO_BUILDINGGREEN, GEO_BUILDINGBLUE, GEO_SPACESHUTTLE, GEO_BUTTON,
GEO_BARREL, GEO_NPC1, GEO_NPC_QUEST1, GEO_NPC_QUEST2,
GEO_INVIS_CURSOR, GEO_TEXT_BOX, GEO_ROBOTHEAD, GEO_ROBOTBODY,
GEO_SWORD, GEO_TYRE, GEO_MINIGAME_PIECE_1, GEO_MINIGAME_PIECE_2,
GEO_MINIGAME_PIECE_3, GEO_MINIGAME_PIECE_4, GEO_MINIGAME_PIECE_5, GEO_MINIGAME_PIECE_6,
GEO_MINIGAME_PIECE_7, GEO_MINIGAME_PIECE_8, GEO_MINIGAME_PIECE_9, GEO_MINIGAME_SELECTOR,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_NUMLIGHTS2,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
rendering of the meshes
void RenderSkybox ()
rendering of skybox
void Rendergroundmesh ()
rendering of ground texture
void RenderScrewDriver ()
void RenderHammer ()
void RenderContainer ()
void RenderGasoline ()
void RenderSpaceShuttle ()
rendering of space shuttle
void RenderStation ()
render everything in the room
void RenderNPC ()
rendering of NPC and quest
void RenderQuestObjects ()
void RenderBarrel ()
void RenderUserInterface (Mesh *mesh, float size, float x, float y)
rendering of user interface
void RenderMinigamePieces ()
rendering minigame pieces & minigame selector
void RenderMinigameOnScreen (Mesh *mesh, float size, float x, float y, float rotate_x)
rendering of the minigame pieces on screen
void RenderMinigameSelectorOnScreen (Mesh *mesh, float size, float x, float y, float rotate_x)
rendering minigame selector on screen
void RenderText (Mesh *mesh, std::string text, Color color)
rendering of the texts using quads
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
rendering of the texts using quads on screen
void RenderImageOnScreen (Mesh *mesh, float size, float x, float y)
rendering of image using quad on screen
void RenderImageOnScreen (Mesh *mesh, float x, float y, float sizeX, float sizeY)
to allow non-uniform scaling of image
void QuestCompleteCheck ()
check if quest is completed
void RenderStuffOnScreen (Mesh *mesh, string direction, float size, float x, float y, float z, float rotate_x, float rotate_y, float rotate_z)
rendering of item taken on screen
void RenderTutorialScreen ()
rendering of tutorial
void renderingSekHeng ()
a method to render Sek Heng and his quest
void renderDialogueBox (const string &name, const string &dialogue)
create a dialogue box easily
void Renderteleporter ()
Teleporter and it's particle effect
void renderChunFei ()
render chunfei npc
void headanimation (double dt)
rendering of chun fei head animation
void renderNPC3 ()
void RenderBuilding ()
rendering of building
void populateArea ()
rendering of environment object
void animateTeleporting (double &dt)
the logic behind animating of teleporting
void animateTeleportation (double &dt)
bool teleport ()
the logic of interaction between the teleporter and player
Private Attributes
bool on_light
Light light [2]
float LSPEED = 10.f
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
NPC npc1
NPC QUEST1
NPC QUEST2
NPC QUEST3
NPC QUEST4
Quest test_quest
Quest One
Quest Two
Quest Three
Quest Four
StationScene door
float lightSwitch
double framePerSecond
float screenWidth
float screenHeight
SekHeng sek_heng_
float headrotating
bool headrotate
short quest_stage
bool Quest1_finished
bool Quest2_finished
bool Quest3_finished
bool Quest4_finished
float teleportCoordY
bool startTeleporting
vector< objectsForDisplay > particleHandlers
double musicTimeDelay
bool tutorialscreen
minigame MiniGame
Detailed Description
inheirited from Scene and made improvised to it. To turn it into a game. This is Scenario 1
Class sceneSP2:
Definition at line 34 of file sceneSP2.h.
Member Enumeration Documentation
enum sceneSP2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LIGHTBALL
GEO_COMIC_TEXT
GEO_LANDVEHICLE
GEO_FLYINGVEHICLE
GEO_SPACE_SKYBOX
GEO_SPACE_GROUNDMESH
GEO_SPACE_WALL
GEO_CRYOSTASIS
GEO_UI
GEO_SCREWDRIVER
GEO_CONTAINER
GEO_GASOLINE
GEO_HAMMER
GEO_STATION
GEO_CHAIR
GEO_TABLE
GEO_BOX
GEO_DOOR
GEO_KEYCARD
GEO_TELEPORTER
GEO_PARTICLE_LIGHT
GEO_PARTICLE_CUBE
GEO_BUILDINGRED
GEO_BUILDINGGREEN
GEO_BUILDINGBLUE
GEO_SPACESHUTTLE
GEO_BUTTON
GEO_BARREL
GEO_NPC1
GEO_NPC_QUEST1
GEO_NPC_QUEST2
GEO_INVIS_CURSOR
GEO_TEXT_BOX
GEO_ROBOTHEAD
GEO_ROBOTBODY
GEO_SWORD
GEO_TYRE
GEO_MINIGAME_PIECE_1
GEO_MINIGAME_PIECE_2
GEO_MINIGAME_PIECE_3
GEO_MINIGAME_PIECE_4
GEO_MINIGAME_PIECE_5
GEO_MINIGAME_PIECE_6
GEO_MINIGAME_PIECE_7
GEO_MINIGAME_PIECE_8
GEO_MINIGAME_PIECE_9
GEO_MINIGAME_SELECTOR
NUM_GEOMETRY
Definition at line 36 of file sceneSP2.h.
enum sceneSP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_NUMLIGHTS2
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 133 of file sceneSP2.h.
Constructor & Destructor Documentation
sceneSP2::sceneSP2 (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
Parameters
screenwidth - width of the screen
screenheight - height of the screen
Definition at line 26 of file sceneSP2.cpp.
sceneSP2::~sceneSP2 ()
destructor
Definition at line 35 of file sceneSP2.cpp.
Member Function Documentation
void sceneSP2::animateTeleportation (double & dt) private
void sceneSP2::animateTeleporting (double & dt) private
the logic behind animating of teleporting
Parameters
dt - frame time
Definition at line 2551 of file sceneSP2.cpp.
References camera, Application::changeIntoScenario2(), Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), Camera3::getCameraXrotation(), Camera3::getCameraYrotation(), Physics::gravitational_pulled(), Camera::position, Camera3::setLocation(), Camera::target, teleportCoordY, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void sceneSP2::Exit () virtual
cleans up the scene
Implements Scene.
Definition at line 1266 of file sceneSP2.cpp.
References m_programID, and m_vertexArrayID.
void sceneSP2::headanimation (double dt) private
rendering of chun fei head animation
Definition at line 1968 of file sceneSP2.cpp.
References headrotate, headrotating, NPC::interaction(), and QUEST3.
Referenced by Update().
void sceneSP2::Init () virtual
initializing whatever is needed for the scene
Implements Scene.
Definition at line 44 of file sceneSP2.cpp.
References camera, Camera3::camType, Light::color, Light::cosCutoff, Light::cosInner, Camera3::cursorCoordX, Camera3::cursorCoordY, Math::DegreeToRadian(), door, Light::exponent, Camera3::FIRST_PERSON, framePerSecond, MeshBuilder::GenerateAxes(), MaterialBuilder::GenerateLambert(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BARREL, GEO_BOX, GEO_BUILDINGBLUE, GEO_BUILDINGGREEN, GEO_BUILDINGRED, GEO_BUTTON, GEO_CHAIR, GEO_COMIC_TEXT, GEO_CONTAINER, GEO_CRYOSTASIS, GEO_DOOR, GEO_GASOLINE, GEO_HAMMER, GEO_INVIS_CURSOR, GEO_KEYCARD, GEO_LANDVEHICLE, GEO_LIGHTBALL, GEO_MINIGAME_PIECE_1, GEO_MINIGAME_PIECE_2, GEO_MINIGAME_PIECE_3, GEO_MINIGAME_PIECE_4, GEO_MINIGAME_PIECE_5, GEO_MINIGAME_PIECE_6, GEO_MINIGAME_PIECE_7, GEO_MINIGAME_PIECE_8, GEO_MINIGAME_PIECE_9, GEO_MINIGAME_SELECTOR, GEO_NPC1, GEO_NPC_QUEST1, GEO_NPC_QUEST2, GEO_PARTICLE_CUBE, GEO_PARTICLE_LIGHT, GEO_ROBOTBODY, GEO_ROBOTHEAD, GEO_SCREWDRIVER, GEO_SPACE_GROUNDMESH, GEO_SPACE_SKYBOX, GEO_SPACE_WALL, GEO_SPACESHUTTLE, GEO_STATION, GEO_SWORD, GEO_TABLE, GEO_TELEPORTER, GEO_TEXT_BOX, GEO_TYRE, GEO_UI, StationScene::getCard1(), StationScene::getCard2(), StationScene::getCardText(), StationScene::getQuestStage(), headrotate, headrotating, minigame::init(), objectsForDisplay::init(), Quest::Init(), NPC::Init(), StationScene::Init(), Camera3::Init(), SekHeng::initDialogues(), Camera3::InitObjects(), Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lightSwitch, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, MiniGame, musicTimeDelay, One, StationScene::openSasame(), particleHandlers, Light::position, Light::power, projectionStack, QUEST1, Quest1_finished, QUEST2, Quest2_finished, QUEST3, Quest3_finished, Quest4_finished, quest_stage, Math::RandFloatMinMax(), StationScene::roomLight(), screenHeight, screenWidth, sek_heng_, Component::Set(), Position::Set(), Vector3::Set(), Color::Set(), Mtx44::SetToPerspective(), Light::spotDirection, startTeleporting, Camera3::storage_of_objects, StationScene::switchText(), teleportCoordY, Mesh::textureID, Three, tutorialscreen, Two, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void sceneSP2::populateArea () private
rendering of environment object
Definition at line 2187 of file sceneSP2.cpp.
References camera, GEO_BARREL, GEO_BOX, GEO_LANDVEHICLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void sceneSP2::QuestCompleteCheck () private
check if quest is completed
Definition at line 2001 of file sceneSP2.cpp.
References Quest1_finished, Quest2_finished, Quest3_finished, and quest_stage.
Referenced by Update().
void sceneSP2::Render () virtual
where the rendering of all the stuff we needed will be here
Implements Scene.
Definition at line 1086 of file sceneSP2.cpp.
References camera, framePerSecond, GEO_COMIC_TEXT, GEO_SPACE_WALL, Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), populateArea(), Camera::position, Light::position, MS::PushMatrix(), RenderBuilding(), renderChunFei(), Rendergroundmesh(), renderingSekHeng(), renderMesh(), RenderMinigamePieces(), RenderNPC(), RenderQuestObjects(), RenderSkybox(), RenderSpaceShuttle(), RenderStation(), Renderteleporter(), RenderTextOnScreen(), RenderTutorialScreen(), MS::Scale(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Light::spotDirection, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void sceneSP2::RenderBarrel () private
void sceneSP2::RenderBuilding () private
rendering of building
Definition at line 1924 of file sceneSP2.cpp.
References camera, GEO_BUILDINGBLUE, GEO_BUILDINGGREEN, GEO_BUILDINGRED, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void sceneSP2::renderChunFei () private
render chunfei npc
Definition at line 2105 of file sceneSP2.cpp.
References camera, GEO_ROBOTBODY, GEO_ROBOTHEAD, GEO_SWORD, NPC::getDialogue(), Quest::getObject1_X(), Quest::getObject1_Z(), headrotating, NPC::interaction(), Application::IsKeyPressed(), Quest::Item1collected(), meshList, modelStack, NPC::NPC_getposition_x(), NPC::NPC_getposition_y(), NPC::NPC_getposition_z(), MS::PopMatrix(), MS::PushMatrix(), Quest2_finished, QUEST3, NPC::quest_complete(), quest_stage, renderDialogueBox(), renderMesh(), RenderStuffOnScreen(), MS::Rotate(), MS::Scale(), Quest::stage(), Camera3::storage_of_objects, Three, and MS::Translate().
Referenced by Render().
void sceneSP2::RenderContainer () private
Definition at line 1529 of file sceneSP2.cpp.
References GEO_HAMMER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), and MS::Translate().
void sceneSP2::renderDialogueBox (const string & name, const string & dialogue) private
create a dialogue box easily
Parameters
name - the name of the interacted object
dialogue - the words said by that interacted object
Definition at line 1881 of file sceneSP2.cpp.
References GEO_COMIC_TEXT, GEO_TEXT_BOX, meshList, RenderImageOnScreen(), and RenderTextOnScreen().
Referenced by renderChunFei(), renderingSekHeng(), RenderNPC(), RenderQuestObjects(), RenderStation(), and Renderteleporter().
void sceneSP2::RenderGasoline () private
Definition at line 1536 of file sceneSP2.cpp.
References GEO_SCREWDRIVER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), and MS::Translate().
void sceneSP2::Rendergroundmesh () private
rendering of ground texture
Definition at line 1506 of file sceneSP2.cpp.
References GEO_SPACE_GROUNDMESH, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), and renderMesh().
Referenced by Render().
void sceneSP2::RenderHammer () private
Definition at line 1522 of file sceneSP2.cpp.
References GEO_GASOLINE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), and MS::Translate().
void sceneSP2::RenderImageOnScreen (Mesh * mesh, float size, float x, float y) private
rendering of image using quad on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 1375 of file sceneSP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by renderDialogueBox(), RenderMinigamePieces(), and RenderTutorialScreen().
void sceneSP2::RenderImageOnScreen (Mesh * mesh, float x, float y, float sizeX, float sizeY) private
to allow non-uniform scaling of image
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
x - x coordinate of the text
y - y coordinate of the text
sizeX - size of the text based on the X-axis
sizeY - size of the text based on the Y-axis
Definition at line 1790 of file sceneSP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
void sceneSP2::renderingSekHeng () private
a method to render Sek Heng and his quest
Definition at line 1751 of file sceneSP2.cpp.
References GEO_HAMMER, GEO_NPC_QUEST1, GameObject::getName(), objectsForDisplay::getObjectposX(), objectsForDisplay::getObjectposY(), objectsForDisplay::getObjectposZ(), SekHeng::getStage(), SekHeng::gottenHammer(), SekHeng::hammer, SekHeng::interaction(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderDialogueBox(), renderMesh(), RenderStuffOnScreen(), SekHeng::returnDialogue(), MS::Scale(), sek_heng_, and MS::Translate().
Referenced by Render().
void sceneSP2::renderMesh (Mesh * mesh, bool enableLight) private
rendering of the meshes
Parameters
mesh - the specific mesh
enableLight - to enable lighting on the object
Definition at line 728 of file sceneSP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by populateArea(), Render(), RenderBuilding(), renderChunFei(), RenderContainer(), RenderGasoline(), Rendergroundmesh(), RenderHammer(), RenderImageOnScreen(), renderingSekHeng(), RenderMinigameOnScreen(), RenderMinigameSelectorOnScreen(), RenderNPC(), RenderQuestObjects(), RenderScrewDriver(), RenderSkybox(), RenderSpaceShuttle(), RenderStation(), RenderStuffOnScreen(), Renderteleporter(), and RenderUserInterface().
void sceneSP2::RenderMinigameOnScreen (Mesh * mesh, float size, float x, float y, float rotate_x) private
rendering of the minigame pieces on screen
Definition at line 2661 of file sceneSP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by RenderMinigamePieces().
void sceneSP2::RenderMinigamePieces () private
rendering minigame pieces & minigame selector
Definition at line 2593 of file sceneSP2.cpp.
References GEO_COMIC_TEXT, GEO_MINIGAME_PIECE_1, GEO_MINIGAME_PIECE_2, GEO_MINIGAME_PIECE_3, GEO_MINIGAME_PIECE_4, GEO_MINIGAME_PIECE_5, GEO_MINIGAME_PIECE_6, GEO_MINIGAME_PIECE_7, GEO_MINIGAME_PIECE_8, GEO_MINIGAME_PIECE_9, GEO_MINIGAME_SELECTOR, GEO_TEXT_BOX, minigame::get_selector_state(), meshList, MiniGame, minigame::minigame_started(), modelStack, minigame::piece1(), minigame::piece2(), minigame::piece3(), minigame::piece4(), minigame::piece5(), minigame::piece6(), minigame::piece7(), minigame::piece8(), minigame::piece9(), MS::PopMatrix(), MS::PushMatrix(), RenderImageOnScreen(), RenderMinigameOnScreen(), RenderMinigameSelectorOnScreen(), RenderTextOnScreen(), and minigame::result().
Referenced by Render().
void sceneSP2::RenderMinigameSelectorOnScreen (Mesh * mesh, float size, float x, float y, float rotate_x) private
rendering minigame selector on screen
Definition at line 2692 of file sceneSP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by RenderMinigamePieces().
void sceneSP2::RenderNPC () private
rendering of NPC and quest
Definition at line 1573 of file sceneSP2.cpp.
References GEO_NPC1, GEO_NPC_QUEST2, NPC::getDialogue(), NPC::interaction(), Application::IsKeyPressed(), meshList, modelStack, NPC::NPC_getposition_x(), NPC::NPC_getposition_y(), NPC::NPC_getposition_z(), One, MS::PopMatrix(), MS::PushMatrix(), QUEST1, Quest1_finished, QUEST2, Quest3_finished, NPC::quest_complete(), quest_stage, renderDialogueBox(), renderMesh(), MS::Scale(), Quest::stage(), MS::Translate(), and Two.
Referenced by Render().
void sceneSP2::renderNPC3 () private
void sceneSP2::RenderQuestObjects () private
Definition at line 1654 of file sceneSP2.cpp.
References GEO_CONTAINER, GEO_GASOLINE, Quest::get_numberof_items(), Quest::getObject1_X(), Quest::getObject1_Z(), Quest::getObject2_X(), Quest::getObject2_Z(), Quest::Item1collected(), Quest::Item2collected(), meshList, modelStack, One, MS::PopMatrix(), MS::PushMatrix(), Quest1_finished, Quest3_finished, renderDialogueBox(), renderMesh(), RenderStuffOnScreen(), MS::Scale(), Quest::stage(), MS::Translate(), and Two.
Referenced by Render().
void sceneSP2::RenderScrewDriver () private
Definition at line 1515 of file sceneSP2.cpp.
References GEO_CONTAINER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), and MS::Translate().
void sceneSP2::RenderSkybox () private
rendering of skybox
Definition at line 1404 of file sceneSP2.cpp.
References GEO_SPACE_SKYBOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), and renderMesh().
Referenced by Render().
void sceneSP2::RenderSpaceShuttle () private
rendering of space shuttle
Definition at line 1554 of file sceneSP2.cpp.
References camera, GEO_SPACESHUTTLE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Scale(), Camera3::storage_of_objects, and MS::Translate().
Referenced by Render().
void sceneSP2::RenderStation () private
render everything in the room
Definition at line 776 of file sceneSP2.cpp.
References camera, door, GEO_BOX, GEO_BUTTON, GEO_CHAIR, GEO_CRYOSTASIS, GEO_DOOR, GEO_KEYCARD, GEO_STATION, GEO_TABLE, StationScene::getCard1(), StationScene::getCard2(), StationScene::getCardText(), StationScene::getQuestStage(), meshList, modelStack, StationScene::openSasame(), MS::PopMatrix(), MS::PushMatrix(), renderDialogueBox(), renderMesh(), MS::Rotate(), MS::Scale(), Camera3::storage_of_objects, StationScene::switchText(), and MS::Translate().
Referenced by Render().
void sceneSP2::RenderStuffOnScreen (Mesh * mesh, string direction, float size, float x, float y, float z, float rotate_x, float rotate_y, float rotate_z) private
rendering of item taken on screen
Definition at line 2027 of file sceneSP2.cpp.
References camera, Camera3::getCameraXcoord(), Camera3::getCameraXrotation(), Camera3::getCameraYcoord(), Camera3::getCameraYrotation(), Camera3::getCameraZcoord(), modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by renderChunFei(), renderingSekHeng(), and RenderQuestObjects().
void sceneSP2::Renderteleporter () private
Teleporter and it's particle effect
Definition at line 1818 of file sceneSP2.cpp.
References camera, GEO_PARTICLE_CUBE, GEO_PARTICLE_LIGHT, GEO_TELEPORTER, meshList, modelStack, particleHandlers, MS::PopMatrix(), Camera::position, MS::PushMatrix(), renderDialogueBox(), renderMesh(), MS::Scale(), sek_heng_, SekHeng::SekHengSayIsOk(), Camera3::storage_of_objects, MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Render().
void sceneSP2::RenderText (Mesh * mesh, std::string text, Color color) private
rendering of the texts using quads
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
Definition at line 1283 of file sceneSP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void sceneSP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
rendering of the texts using quads on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 1323 of file sceneSP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), renderDialogueBox(), RenderMinigamePieces(), and RenderTutorialScreen().
void sceneSP2::RenderTutorialScreen () private
rendering of tutorial
Definition at line 2574 of file sceneSP2.cpp.
References GEO_COMIC_TEXT, GEO_TEXT_BOX, meshList, RenderImageOnScreen(), RenderTextOnScreen(), and tutorialscreen.
Referenced by Render().
void sceneSP2::RenderUserInterface (Mesh * mesh, float size, float x, float y) private
rendering of user interface
Parameters
mesh - a pointer to the specific mesh
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 1474 of file sceneSP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
void sceneSP2::reset ()
reset the entire scene 1 /*
Definition at line 694 of file sceneSP2.cpp.
References camera, door, minigame::init(), Quest::Init(), MiniGame, musicTimeDelay, npc1, One, Quest1_finished, Quest2_finished, Quest3_finished, Quest4_finished, quest_stage, NPC::reset(), Quest::reset(), StationScene::reset(), Camera3::Reset(), SekHeng::reset(), sek_heng_, startTeleporting, teleportCoordY, test_quest, Three, tutorialscreen, and Two.
Referenced by Update().
bool sceneSP2::teleport () private
the logic of interaction between the teleporter and player
Returns
- true if player is inisde it's interacting boundary
- false if the player is outside it's interacting boundary
Definition at line 1897 of file sceneSP2.cpp.
References camera, Camera::position, Camera3::storage_of_objects, Vector3::x, and Vector3::z.
Referenced by Update().
void sceneSP2::Update (double dt) virtual
where the logic of the game is, and update
Parameters
dt - time frame
Implements Scene.
Definition at line 529 of file sceneSP2.cpp.
References SekHeng::activateQuest(), animateTeleporting(), camera, Application::changeIntoScenario2(), Application::changeIntoScenario3(), Quest::check_quest(), door, SekHeng::FinishedQuest(), framePerSecond, Camera3::getCameraXcoord(), Camera3::getCameraYcoord(), Camera3::getCameraZcoord(), headanimation(), Application::IsKeyPressed(), light, LSPEED, MiniGame, minigame::minigame_started(), Application::musics, musicTimeDelay, npc1, One, StationScene::openSasame(), particleHandlers, BGMDriven::playDarthVaderBackground(), BGMDriven::playGateEffect(), Light::position, QUEST1, QUEST2, QUEST3, NPC::quest_given(), quest_stage, QuestCompleteCheck(), Math::RandFloatMinMax(), reset(), minigame::result(), StationScene::roomLight(), sek_heng_, SekHeng::SekHengSayIsOk(), Position::Set(), startTeleporting, Camera3::storage_of_objects, Camera::target, teleport(), Three, tutorialscreen, Two, Camera::up, minigame::update(), NPC::update(), StationScene::update(), SekHeng::Update(), Quest::Update(), Camera3::Update(), BGMDriven::updatePlayerPos(), Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Camera3 sceneSP2::camera private
Definition at line 220 of file sceneSP2.h.
Referenced by animateTeleporting(), Init(), populateArea(), Render(), RenderBuilding(), renderChunFei(), RenderSpaceShuttle(), RenderStation(), RenderStuffOnScreen(), Renderteleporter(), reset(), teleport(), and Update().
StationScene sceneSP2::door private
Definition at line 239 of file sceneSP2.h.
Referenced by Init(), RenderStation(), reset(), and Update().
Quest sceneSP2::Four private
Definition at line 236 of file sceneSP2.h.
double sceneSP2::framePerSecond private
Definition at line 249 of file sceneSP2.h.
Referenced by Init(), Render(), and Update().
bool sceneSP2::headrotate private
Definition at line 266 of file sceneSP2.h.
Referenced by headanimation(), and Init().
float sceneSP2::headrotating private
Definition at line 265 of file sceneSP2.h.
Referenced by headanimation(), Init(), and renderChunFei().
Light sceneSP2::light[2] private
Definition at line 188 of file sceneSP2.h.
Referenced by Init(), Render(), and Update().
float sceneSP2::lightSwitch private
Definition at line 240 of file sceneSP2.h.
Referenced by Init().
float sceneSP2::LSPEED = 10.f private
Definition at line 189 of file sceneSP2.h.
Referenced by Update().
unsigned sceneSP2::m_parameters[U_TOTAL] private
Definition at line 218 of file sceneSP2.h.
Referenced by Init(), Render(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned sceneSP2::m_programID private
Definition at line 217 of file sceneSP2.h.
Referenced by Exit(), and Init().
unsigned sceneSP2::m_vertexArrayID private
Definition at line 214 of file sceneSP2.h.
Referenced by Exit(), and Init().
Mesh* sceneSP2::meshList[NUM_GEOMETRY] private
Definition at line 215 of file sceneSP2.h.
Referenced by Init(), populateArea(), Render(), RenderBuilding(), renderChunFei(), RenderContainer(), renderDialogueBox(), RenderGasoline(), Rendergroundmesh(), RenderHammer(), renderingSekHeng(), RenderMinigamePieces(), RenderNPC(), RenderQuestObjects(), RenderScrewDriver(), RenderSkybox(), RenderSpaceShuttle(), RenderStation(), Renderteleporter(), and RenderTutorialScreen().
minigame sceneSP2::MiniGame private
Definition at line 304 of file sceneSP2.h.
Referenced by Init(), RenderMinigamePieces(), reset(), and Update().
MS sceneSP2::modelStack private
Definition at line 222 of file sceneSP2.h.
Referenced by populateArea(), Render(), RenderBuilding(), renderChunFei(), RenderContainer(), RenderGasoline(), Rendergroundmesh(), RenderHammer(), RenderImageOnScreen(), renderingSekHeng(), renderMesh(), RenderMinigameOnScreen(), RenderMinigamePieces(), RenderMinigameSelectorOnScreen(), RenderNPC(), RenderQuestObjects(), RenderScrewDriver(), RenderSkybox(), RenderSpaceShuttle(), RenderStation(), RenderStuffOnScreen(), Renderteleporter(), RenderText(), RenderTextOnScreen(), and RenderUserInterface().
double sceneSP2::musicTimeDelay private
Definition at line 297 of file sceneSP2.h.
Referenced by Init(), reset(), and Update().
NPC sceneSP2::npc1 private
Definition at line 225 of file sceneSP2.h.
Referenced by reset(), and Update().
bool sceneSP2::on_light private
Definition at line 187 of file sceneSP2.h.
Quest sceneSP2::One private
Definition at line 233 of file sceneSP2.h.
Referenced by Init(), RenderNPC(), RenderQuestObjects(), reset(), and Update().
vector<objectsForDisplay> sceneSP2::particleHandlers private
Definition at line 293 of file sceneSP2.h.
Referenced by Init(), Renderteleporter(), and Update().
MS sceneSP2::projectionStack private
Definition at line 222 of file sceneSP2.h.
Referenced by Init(), RenderImageOnScreen(), renderMesh(), RenderMinigameOnScreen(), RenderMinigameSelectorOnScreen(), RenderText(), RenderTextOnScreen(), and RenderUserInterface().
NPC sceneSP2::QUEST1 private
Definition at line 226 of file sceneSP2.h.
Referenced by Init(), RenderNPC(), and Update().
bool sceneSP2::Quest1_finished private
Definition at line 277 of file sceneSP2.h.
Referenced by Init(), QuestCompleteCheck(), RenderNPC(), RenderQuestObjects(), and reset().
NPC sceneSP2::QUEST2 private
Definition at line 227 of file sceneSP2.h.
Referenced by Init(), RenderNPC(), and Update().
bool sceneSP2::Quest2_finished private
Definition at line 278 of file sceneSP2.h.
Referenced by Init(), QuestCompleteCheck(), renderChunFei(), and reset().
NPC sceneSP2::QUEST3 private
Definition at line 228 of file sceneSP2.h.
Referenced by headanimation(), Init(), renderChunFei(), and Update().
bool sceneSP2::Quest3_finished private
Definition at line 279 of file sceneSP2.h.
Referenced by Init(), QuestCompleteCheck(), RenderNPC(), RenderQuestObjects(), and reset().
NPC sceneSP2::QUEST4 private
Definition at line 229 of file sceneSP2.h.
bool sceneSP2::Quest4_finished private
Definition at line 280 of file sceneSP2.h.
Referenced by Init(), and reset().
short sceneSP2::quest_stage private
Definition at line 276 of file sceneSP2.h.
Referenced by Init(), QuestCompleteCheck(), renderChunFei(), RenderNPC(), reset(), and Update().
float sceneSP2::screenHeight private
Definition at line 250 of file sceneSP2.h.
Referenced by Init().
float sceneSP2::screenWidth private
Definition at line 250 of file sceneSP2.h.
Referenced by Init().
SekHeng sceneSP2::sek_heng_ private
Definition at line 253 of file sceneSP2.h.
Referenced by Init(), renderingSekHeng(), Renderteleporter(), reset(), and Update().
bool sceneSP2::startTeleporting private
Definition at line 288 of file sceneSP2.h.
Referenced by Init(), reset(), and Update().
float sceneSP2::teleportCoordY private
Definition at line 287 of file sceneSP2.h.
Referenced by animateTeleporting(), Init(), and reset().
Quest sceneSP2::test_quest private
Definition at line 232 of file sceneSP2.h.
Referenced by reset().
Quest sceneSP2::Three private
Definition at line 235 of file sceneSP2.h.
Referenced by Init(), renderChunFei(), reset(), and Update().
bool sceneSP2::tutorialscreen private
Definition at line 301 of file sceneSP2.h.
Referenced by Init(), RenderTutorialScreen(), reset(), and Update().
Quest sceneSP2::Two private
Definition at line 234 of file sceneSP2.h.
Referenced by Init(), RenderNPC(), RenderQuestObjects(), reset(), and Update().
MS sceneSP2::viewStack private
Definition at line 222 of file sceneSP2.h.
Referenced by Render(), RenderImageOnScreen(), renderMesh(), RenderMinigameOnScreen(), RenderMinigameSelectorOnScreen(), RenderText(), RenderTextOnScreen(), and RenderUserInterface().
The documentation for this class was generated from the following files:
MyGraphics/Source/sceneSP2.h
MyGraphics/Source/sceneSP2.cpp