My Application: creditScene Class Reference
creditScene Class Reference
The logic class of credit scene.
#include <creditScene.h>
Public Member Functions
creditScene ()
a default constructor, with all variables becoming default value
~creditScene ()
a destructor
void initCredit (char *fileLocation)
a Data Driven method which will load the position of the people and their names
void updateCredit (double &dt)
the method to update the logic of the credit scene
void activateCredit ()
a method function which will activate the credits which are the people's position and their names.
bool goRollCredit ()
return whether to roll the credits or not
float getRollingTitle ()
a getter function that allows user to get the position y of the credit title in this case 'Prologue Ended'
float getRollingTitleCaption ()
a getter function that allows user to get the position y of the credit title captions in this case 'To Be Continued' and 'Plz buy our expansion pack in the future'
float getMovePositionY ()
a getter function that will get the credit's position y in this case the people's position and their names.
void reset ()
a method that all the variables inside this class to it's default values
Data Fields
vector< string > position
vector< string > names
Private Attributes
float rollingTitle
float rollingTitleCaption
bool rollCredits
float movePositionY
Detailed Description
The logic class of credit scene.
Class creditScene:
Definition at line 26 of file creditScene.h.
Constructor & Destructor Documentation
creditScene::creditScene ()
a default constructor, with all variables becoming default value
Definition at line 11 of file creditScene.cpp.
creditScene::~creditScene ()
a destructor
Definition at line 21 of file creditScene.cpp.
Member Function Documentation
void creditScene::activateCredit ()
a method function which will activate the credits which are the people's position and their names.
Definition at line 123 of file creditScene.cpp.
References rollCredits.
Referenced by scene2_SP2::Ending().
float creditScene::getMovePositionY ()
a getter function that will get the credit's position y in this case the people's position and their names.
Definition at line 133 of file creditScene.cpp.
References movePositionY.
Referenced by scene2_SP2::rollingCredits().
float creditScene::getRollingTitle ()
a getter function that allows user to get the position y of the credit title in this case 'Prologue Ended'
Returns
- the float values of coord Y of rolling title
Definition at line 101 of file creditScene.cpp.
References rollingTitle.
Referenced by scene2_SP2::rollingCredits().
float creditScene::getRollingTitleCaption ()
a getter function that allows user to get the position y of the credit title captions in this case 'To Be Continued' and 'Plz buy our expansion pack in the future'
Returns
- the float values of coord Y of rolling title captions
Definition at line 113 of file creditScene.cpp.
References rollingTitleCaption.
Referenced by scene2_SP2::rollingCredits().
bool creditScene::goRollCredit ()
return whether to roll the credits or not
Returns
true - if rollCredits is true
false - if rollCredits is false
Definition at line 86 of file creditScene.cpp.
References rollCredits.
Referenced by scene2_SP2::rollingCredits(), and scene2_SP2::Update().
void creditScene::initCredit (char * fileLocation)
a Data Driven method which will load the position of the people and their names
Parameters
fileLocation - the path name to the text file
Definition at line 32 of file creditScene.cpp.
References names, and position.
Referenced by scene2_SP2::Init().
void creditScene::reset ()
a method that all the variables inside this class to it's default values
Definition at line 142 of file creditScene.cpp.
References movePositionY, rollCredits, rollingTitle, and rollingTitleCaption.
Referenced by scene2_SP2::Reset().
void creditScene::updateCredit (double & dt)
the method to update the logic of the credit scene
Parameters
dt - frame time
Definition at line 67 of file creditScene.cpp.
References movePositionY, rollingTitle, and rollingTitleCaption.
Referenced by scene2_SP2::Update().
Field Documentation
float creditScene::movePositionY private
Definition at line 49 of file creditScene.h.
Referenced by getMovePositionY(), reset(), and updateCredit().
vector<string> creditScene::names
Definition at line 41 of file creditScene.h.
Referenced by initCredit(), and scene2_SP2::rollingCredits().
vector<string> creditScene::position
Definition at line 40 of file creditScene.h.
Referenced by initCredit(), and scene2_SP2::rollingCredits().
bool creditScene::rollCredits private
Definition at line 48 of file creditScene.h.
Referenced by activateCredit(), goRollCredit(), and reset().
float creditScene::rollingTitle private
Definition at line 46 of file creditScene.h.
Referenced by getRollingTitle(), reset(), and updateCredit().
float creditScene::rollingTitleCaption private
Definition at line 47 of file creditScene.h.
Referenced by getRollingTitleCaption(), reset(), and updateCredit().
The documentation for this class was generated from the following files:
MyGraphics/Source/creditScene.h
MyGraphics/Source/creditScene.cpp