My Application: SekHeng Class Reference
SekHeng Class Reference
#include <SekHeng.h>
Public Member Functions
SekHeng ()
a default constructor, with all variables becoming default value
~SekHeng ()
a destructor
void initDialogues (const char *fileLocation, Camera3 &camera)
a Data Driven function that will initialised it's dialogue
void Update (double dt)
a method function which will update the logic behind the interaction with Sek Heng
string returnDialogue ()
a getter function which user can get the dialogue from Sek Heng
bool interaction ()
to check whether the player in within it's interacting boundary
void preventSpamming ()
Prevention of the dialogue from running to fast if player is holding 'E'
void activateQuest ()
a method function which will activate the Sek Heng's quest
bool SekHengSayIsOk ()
check whether Sek Heng's quest is completed
void FinishedQuest ()
a method function which will allows teleportation and new dialogue upon finishing Sek Heng's quest
bool gottenHammer ()
check whether player has gotten the hammer
short getStage ()
a getter function that returns the dialogue which Sek Heng will say in 3 different state which are when Sek Heng is waiting for other quests to be completed, Sek Heng is waiting for the player to finish his quest, and Sek Heng's quest is completed
void reset ()
a method to completely reset the Sek Heng's variable to it's default state
Public Member Functions inherited from objectsForDisplay
objectsForDisplay ()
Default Constructor
~objectsForDisplay ()
Destructor
void init (const char *fileLocation)
initialised it's values through text file reader
void init (Vector3 pos, float boundaryX, float boundaryZ, string name)
initialised it's variables by passing in parameter
bool boundaryCheck (const float &playerPosX, const float &playerPosZ)
the boundary check with the camera's position
float getObjectposX ()
get this object's X coordinate
float getObjectposY ()
get this object's Y coordinate
float getObjectposZ ()
get this object's Z coordinate
float getBoundaryRadiusX ()
get this object's X boundary range
float getBoundaryRadiusZ ()
get this object's Z boundary range
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Data Fields
objectsForDisplay hammer
Data Fields inherited from objectsForDisplay
Vector3 objectPos
Vector3 originalPos
Private Member Functions
bool interactingWithItem ()
to check whether the player in within Sek Heng's hammer interacting boundary
Private Attributes
Camera3 * dub_camera
float interatingRadius
double time
short stage
short order_of_text
map< short, vector< string > > dialogues
bool isOkay
bool hammerInHand
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Protected Attributes inherited from objectsForDisplay
float boundaryRadiusX
float boundaryRadiusZ
Protected Attributes inherited from GameObject
string Name_
Detailed Description
Definition at line 30 of file SekHeng.h.
Constructor & Destructor Documentation
SekHeng::SekHeng ()
a default constructor, with all variables becoming default value
Definition at line 11 of file SekHeng.cpp.
References hammer, and objectsForDisplay::init().
SekHeng::~SekHeng ()
a destructor
Definition at line 22 of file SekHeng.cpp.
Member Function Documentation
void SekHeng::activateQuest ()
a method function which will activate the Sek Heng's quest
Definition at line 115 of file SekHeng.cpp.
References hammerInHand, and stage.
Referenced by sceneSP2::Update().
void SekHeng::FinishedQuest ()
a method function which will allows teleportation and new dialogue upon finishing Sek Heng's quest
Definition at line 184 of file SekHeng.cpp.
References isOkay, and stage.
Referenced by Update(), and sceneSP2::Update().
short SekHeng::getStage ()
a getter function that returns the dialogue which Sek Heng will say in 3 different state which are when Sek Heng is waiting for other quests to be completed, Sek Heng is waiting for the player to finish his quest, and Sek Heng's quest is completed
Returns
- the order of dialogues
Definition at line 234 of file SekHeng.cpp.
References stage.
Referenced by sceneSP2::renderingSekHeng().
bool SekHeng::gottenHammer ()
check whether player has gotten the hammer
Returns
- true if player has interacted with the hammer
- false if the player has not interacted with the hammer
Definition at line 218 of file SekHeng.cpp.
References hammerInHand.
Referenced by sceneSP2::renderingSekHeng().
void SekHeng::initDialogues (const char * fileLocation, Camera3 & camera)
a Data Driven function that will initialised it's dialogue
Parameters
fileLocation - the path name to the file's location
camera - a reference pointer to the scene's camera
Definition at line 35 of file SekHeng.cpp.
References dialogues, and dub_camera.
Referenced by sceneSP2::Init().
bool SekHeng::interactingWithItem () private
to check whether the player in within Sek Heng's hammer interacting boundary
Returns
- true if the player is outside Sek Heng's hammer interacting boundary
- false if the player is inside Sek Heng's hammer interacting boundary
Definition at line 198 of file SekHeng.cpp.
References dub_camera, objectsForDisplay::getBoundaryRadiusX(), objectsForDisplay::getBoundaryRadiusZ(), objectsForDisplay::getObjectposX(), objectsForDisplay::getObjectposZ(), hammer, Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
bool SekHeng::interaction ()
to check whether the player in within it's interacting boundary
Returns
- true if the player is outside it's interacting boundary
- false if the player is inside it's interacting boundary
Definition at line 131 of file SekHeng.cpp.
References objectsForDisplay::boundaryRadiusX, objectsForDisplay::boundaryRadiusZ, dub_camera, Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), interatingRadius, objectsForDisplay::objectPos, order_of_text, Vector3::x, and Vector3::z.
Referenced by sceneSP2::renderingSekHeng(), and Update().
void SekHeng::preventSpamming ()
Prevention of the dialogue from running to fast if player is holding 'E'
Definition at line 148 of file SekHeng.cpp.
References dialogues, Application::IsKeyPressed(), order_of_text, stage, and time.
Referenced by Update().
void SekHeng::reset ()
a method to completely reset the Sek Heng's variable to it's default state
Definition at line 243 of file SekHeng.cpp.
References hammer, hammerInHand, objectsForDisplay::init(), isOkay, objectsForDisplay::objectPos, order_of_text, objectsForDisplay::originalPos, stage, and time.
Referenced by sceneSP2::reset().
string SekHeng::returnDialogue ()
a getter function which user can get the dialogue from Sek Heng
Returns
- a string of the dialogue
Definition at line 106 of file SekHeng.cpp.
References dialogues, order_of_text, and stage.
Referenced by sceneSP2::renderingSekHeng().
bool SekHeng::SekHengSayIsOk ()
check whether Sek Heng's quest is completed
Returns
- true if Sek Heng's quest is completed
- false if Sek Heng's quest is incomplete
Definition at line 169 of file SekHeng.cpp.
References isOkay.
Referenced by sceneSP2::Renderteleporter(), and sceneSP2::Update().
void SekHeng::Update (double dt)
a method function which will update the logic behind the interaction with Sek Heng
Parameters
dt - frame time
Definition at line 81 of file SekHeng.cpp.
References FinishedQuest(), hammerInHand, interactingWithItem(), interaction(), Application::IsKeyPressed(), preventSpamming(), stage, and time.
Referenced by sceneSP2::Update().
Field Documentation
map<short, vector<string> > SekHeng::dialogues private
Definition at line 60 of file SekHeng.h.
Referenced by initDialogues(), preventSpamming(), and returnDialogue().
Camera3* SekHeng::dub_camera private
Definition at line 54 of file SekHeng.h.
Referenced by initDialogues(), interactingWithItem(), and interaction().
objectsForDisplay SekHeng::hammer
Definition at line 47 of file SekHeng.h.
Referenced by interactingWithItem(), sceneSP2::renderingSekHeng(), reset(), and SekHeng().
bool SekHeng::hammerInHand private
Definition at line 64 of file SekHeng.h.
Referenced by activateQuest(), gottenHammer(), reset(), and Update().
float SekHeng::interatingRadius private
Definition at line 55 of file SekHeng.h.
Referenced by interaction().
bool SekHeng::isOkay private
Definition at line 62 of file SekHeng.h.
Referenced by FinishedQuest(), reset(), and SekHengSayIsOk().
short SekHeng::order_of_text private
Definition at line 58 of file SekHeng.h.
Referenced by interaction(), preventSpamming(), reset(), and returnDialogue().
short SekHeng::stage private
Definition at line 57 of file SekHeng.h.
Referenced by activateQuest(), FinishedQuest(), getStage(), preventSpamming(), reset(), returnDialogue(), and Update().
double SekHeng::time private
Definition at line 56 of file SekHeng.h.
Referenced by preventSpamming(), reset(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/SekHeng.h
MyGraphics/Source/SekHeng.cpp