My Application: Application Class Reference
Application Class Reference
Where the glfw and glew do their stuff At the run will be where the game stuff comes in.
#include <Application.h>
Public Member Functions
Application ()
Default Constructor
~Application ()
Destructor
void Init ()
Where the initialization of the glfw and glew, window size, and window's location
void Run ()
Initializing of the scene, and starting of the game
void Exit ()
Calls for the destroying of windows and cleaning up GLFW
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
Define the key input callback and prevent the key from pressing twice
static void changeIntoScenario3 ()
a method to transit to scenario 3
static void changeIntoScenario1 ()
a method to transit to scenario 1
static void changeIntoScenario2 ()
a method to transit to scenario 2
Static Public Attributes
static BGMDriven * musics
Private Attributes
StopWatch m_timer
Static Private Attributes
static Scene * scene
static Scene * scenario1
static Scene * scenario3
static Scene * scenario2
Detailed Description
Where the glfw and glew do their stuff At the run will be where the game stuff comes in.
Class Application:
Definition at line 29 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Default Constructor
Definition at line 71 of file Application.cpp.
Application::~Application ()
Destructor
Definition at line 81 of file Application.cpp.
Member Function Documentation
void Application::changeIntoScenario1 () static
a method to transit to scenario 1
Definition at line 270 of file Application.cpp.
References scenario1, and scene.
Referenced by scene3_SP2::Update(), and scene2_SP2::Update().
void Application::changeIntoScenario2 () static
a method to transit to scenario 2
Definition at line 280 of file Application.cpp.
References scenario2, and scene.
Referenced by sceneSP2::animateTeleporting(), scene2_SP2::Update(), and sceneSP2::Update().
void Application::changeIntoScenario3 () static
a method to transit to scenario 3
Definition at line 261 of file Application.cpp.
References scenario3, and scene.
Referenced by scene3_SP2::Update(), and sceneSP2::Update().
void Application::Exit ()
Calls for the destroying of windows and cleaning up GLFW
Definition at line 247 of file Application.cpp.
References m_window.
Referenced by main().
void Application::Init ()
Where the initialization of the glfw and glew, window size, and window's location
Definition at line 111 of file Application.cpp.
References error_callback(), m_window, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Define the key input callback and prevent the key from pressing twice
Returns
- whether the key that the player pressed is true
Definition at line 60 of file Application.cpp.
Referenced by Camera3::cameraMovement(), minigame::changePieceRotation(), StationScene::getCard1(), StationScene::getCard2(), StationScene::getQuestStage(), NumPad::NumpadProgram(), StationScene::openSasame(), rot_civ::preventSpamming(), SekHeng::preventSpamming(), NPC::quest_complete(), sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), scene2_SP2::RenderVault(), StationScene::roomLight(), Run(), minigame::selection_pointer(), Camera::Update(), NumPad::Update(), NPC::update(), SekHeng::Update(), Quest::Update(), Camera3::Update(), scene3SP2::Update(), scene3_SP2::Update(), scene2_SP2::Update(), sceneSP2::Update(), and scene3_SP2::updateIntructions().
void Application::Run ()
Initializing of the scene, and starting of the game
Definition at line 177 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Scene::Init(), BGMDriven::init(), IsKeyPressed(), m_timer, m_window, musics, Scene::Render(), scenario1, scenario2, scenario3, scene, StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
Field Documentation
StopWatch Application::m_timer private
Definition at line 50 of file Application.h.
Referenced by Run().
BGMDriven * Application::musics static
Definition at line 43 of file Application.h.
Referenced by scene3_SP2::animateWarp(), scene2_SP2::Ending(), scene2_SP2::renderDeadPool(), scene2_SP2::rollingCredits(), Run(), scene3_SP2::Update(), scene2_SP2::Update(), sceneSP2::Update(), and scene2_SP2::VaultAnimation().
Scene * Application::scenario1 static private
Definition at line 46 of file Application.h.
Referenced by changeIntoScenario1(), and Run().
Scene * Application::scenario2 static private
Definition at line 48 of file Application.h.
Referenced by changeIntoScenario2(), and Run().
Scene * Application::scenario3 static private
Definition at line 47 of file Application.h.
Referenced by changeIntoScenario3(), and Run().
Scene * Application::scene static private
Definition at line 45 of file Application.h.
Referenced by changeIntoScenario1(), changeIntoScenario2(), changeIntoScenario3(), and Run().
The documentation for this class was generated from the following files:
MyGraphics/Source/Application.h
MyGraphics/Source/Application.cpp