My Application: Camera3 Class Reference
Camera3 Class Reference
First Person Camera included Extremely Complex functions of the camera which incorporates mouse control.
#include <Camera3.h>
Public Types
enum CameraType { COMMON, FIRST_PERSON, TOTAL_CAMERAS_TYPE }
Public Member Functions
Camera3 ()
Default constructor.
~Camera3 ()
Destructor.
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Initialize camera.
virtual void Init (const char *fileLocation)
Initialize camera.
virtual void Update (double dt)
To be called every frame. Camera will get user inputs and update its position and orientation.
virtual void Reset ()
Reset the camera settings
void InitObjects (const char *fileLocation)
a Data Driven method to initialise a bunch of static objects that can be used to render the coordinates of GameObject, and as a bounds check with the player's coordinate
void setLocation (float x, float y, float z)
Setting the coordinates of the camera's position.
void setRotation (float rotateX, float rotateY)
a method to set the rotation / target of the camera
float getCameraXcoord ()
getting camera's position of x coordinate
float getCameraZcoord ()
getting camera's position of z coordinate
float getCameraYcoord ()
getting camera's position of y coordinate
float getCameraYrotation ()
getting camera's rotation based on the y axis
float getCameraXrotation ()
getting camera's rotation based on the x axis
Public Member Functions inherited from Camera
Camera ()
Default constructor.
~Camera ()
Destructor.
void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Initialize camera.
void Reset ()
Reset the camera settings.
void Update (double dt)
To be called every frame. Camera will get user inputs and update its position and orientation.
Data Fields
enum Camera3::CameraType camType
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
float defaultCameraYrotation
float defaultCameraXrotation
float cursorCoordX
float cursorCoordY
vector< objectsForDisplay > storage_of_objects
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Private Member Functions
void rotateCamera (double dt)
rotation of the camera based on the mouse movement
void cameraMovement (double dt)
An improved camera movement based on first person
bool boundsCheckXaxis (const float &x, const float &posX)
boundary check with the player based on the X-axis, cheaper to compute and determines where the player can go
bool boundsCheckZaxis (const float &z, const float &posZ)
boundary check with the player based on the Z-axis, cheaper to compute and determines where the player can go
Private Attributes
float CameraXrotation
float CameraYrotation
float maxCameraXrotation
float minCameraXrotation
float cameraSpeed
float boundaryX
float boundaryZ
Vector3 invisibleCrossHair
float crossHairRadius
Additional Inherited Members
Protected Member Functions inherited from Camera
float moveX (float phi, float theta)
Move the x coordinate of the camera in a circular way
float moveY (float phi, float theta)
Move the y coordinate of the camera in a circular way
float moveZ (float phi, float theta)
Move the z coordinate of the camera in a circular way
Detailed Description
First Person Camera included Extremely Complex functions of the camera which incorporates mouse control.
Class Camera3:
Definition at line 26 of file Camera3.h.
Member Enumeration Documentation
enum Camera3::CameraType
Enumerator
COMMON
FIRST_PERSON
TOTAL_CAMERAS_TYPE
Definition at line 29 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Default constructor.
Definition at line 19 of file Camera3.cpp.
Camera3::~Camera3 ()
Destructor.
Definition at line 30 of file Camera3.cpp.
References storage_of_objects.
Member Function Documentation
bool Camera3::boundsCheckXaxis (const float & x, const float & posX) private
boundary check with the player based on the X-axis, cheaper to compute and determines where the player can go
Parameters
x - the distance from the origin based on the X-axis, in both direction
posX - x coordinate of player's position
Definition at line 442 of file Camera3.cpp.
Referenced by cameraMovement().
bool Camera3::boundsCheckZaxis (const float & z, const float & posZ) private
boundary check with the player based on the Z-axis, cheaper to compute and determines where the player can go
Parameters
z - the distance from the origin based on the Z-axis, in both direction
posZ - z coordinate of player's position
Definition at line 460 of file Camera3.cpp.
Referenced by cameraMovement().
void Camera3::cameraMovement (double dt) private
An improved camera movement based on first person
Parameters
dt - frame time
Definition at line 290 of file Camera3.cpp.
References boundaryX, boundaryZ, boundsCheckXaxis(), boundsCheckZaxis(), cameraSpeed, CameraYrotation, Math::DegreeToRadian(), Application::IsKeyPressed(), Camera::position, storage_of_objects, Vector3::x, and Vector3::z.
Referenced by Update().
float Camera3::getCameraXcoord ()
getting camera's position of x coordinate
Returns
- x coordinate of camera's position
Definition at line 359 of file Camera3.cpp.
References Camera::position, and Vector3::x.
Referenced by rot_civ::interaction(), NPC::interaction(), SekHeng::interaction(), NumPad::interaction(), scene3_SP2::Render(), scene2_SP2::Render(), sceneSP2::Render(), sceneSP2::RenderStuffOnScreen(), Quest::Update(), and sceneSP2::Update().
float Camera3::getCameraXrotation ()
getting camera's rotation based on the x axis
Returns
- camera's rotational angle based on the x axis
Definition at line 400 of file Camera3.cpp.
References CameraXrotation.
Referenced by sceneSP2::animateTeleporting(), scene2_SP2::Ending(), sceneSP2::RenderStuffOnScreen(), and scene3_SP2::Update().
float Camera3::getCameraYcoord ()
getting camera's position of y coordinate
Returns
- y coordinate of camera's position
Definition at line 386 of file Camera3.cpp.
References Camera::position, and Vector3::y.
Referenced by scene3_SP2::Render(), sceneSP2::RenderStuffOnScreen(), and sceneSP2::Update().
float Camera3::getCameraYrotation ()
getting camera's rotation based on the y axis
Returns
- camera's rotational angle based on the y axis
Definition at line 412 of file Camera3.cpp.
References CameraYrotation.
Referenced by sceneSP2::animateTeleporting(), scene2_SP2::Ending(), sceneSP2::RenderStuffOnScreen(), and scene3_SP2::Update().
float Camera3::getCameraZcoord ()
getting camera's position of z coordinate
Returns
- z coordinate of camera's position
Definition at line 372 of file Camera3.cpp.
References Camera::position, and Vector3::z.
Referenced by rot_civ::interaction(), NPC::interaction(), SekHeng::interaction(), NumPad::interaction(), scene3_SP2::Render(), scene2_SP2::Render(), sceneSP2::Render(), sceneSP2::RenderStuffOnScreen(), Quest::Update(), and sceneSP2::Update().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Initialize camera.
Parameters
pos - position of camera
target - where the camera is looking at
up - up vector of camera
mass - mass of the camera which is default to 0
Definition at line 46 of file Camera3.cpp.
References cameraSpeed, CameraXrotation, CameraYrotation, camType, COMMON, Vector3::Cross(), defaultCameraXrotation, defaultCameraYrotation, defaultPosition, defaultTarget, defaultUp, maxCameraXrotation, minCameraXrotation, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, and Vector3::y.
Referenced by LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), and sceneSP2::Init().
void Camera3::Init (const char * fileLocation) virtual
Initialize camera.
Parameters
fileLocation - path name to the file
Definition at line 73 of file Camera3.cpp.
References boundaryX, boundaryZ, cameraSpeed, CameraXrotation, CameraYrotation, camType, Vector3::Cross(), defaultCameraXrotation, defaultCameraYrotation, defaultPosition, defaultUp, Math::DegreeToRadian(), FIRST_PERSON, maxCameraXrotation, minCameraXrotation, Camera::position, Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
void Camera3::InitObjects (const char * fileLocation)
a Data Driven method to initialise a bunch of static objects that can be used to render the coordinates of GameObject, and as a bounds check with the player's coordinate
Parameters
fileLocation - the path name to the text file
Definition at line 476 of file Camera3.cpp.
References objectsForDisplay::init(), and storage_of_objects.
Referenced by scene3_SP2::Init(), scene2_SP2::Init(), and sceneSP2::Init().
void Camera3::Reset () virtual
Reset the camera settings
Definition at line 251 of file Camera3.cpp.
References CameraXrotation, CameraYrotation, defaultCameraXrotation, defaultCameraYrotation, defaultPosition, defaultTarget, defaultUp, Camera::position, Camera::target, and Camera::up.
Referenced by scene3_SP2::reset(), sceneSP2::reset(), scene2_SP2::Reset(), and Update().
void Camera3::rotateCamera (double dt) private
rotation of the camera based on the mouse movement
Parameters
dt - frame time
Definition at line 268 of file Camera3.cpp.
References CameraXrotation, CameraYrotation, Math::Clamp(), Vector3::Cross(), cursorCoordX, cursorCoordY, defaultUp, Math::DegreeToRadian(), maxCameraXrotation, minCameraXrotation, Camera::position, Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void Camera3::setLocation (float x, float y, float z)
Setting the coordinates of the camera's position.
Parameters
x - coordinate x of the camera's position
y - coordinate y of the camera's position
z - coordinate z of the camera's position
Definition at line 426 of file Camera3.cpp.
References Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by sceneSP2::animateTeleporting(), and scene2_SP2::Ending().
void Camera3::setRotation (float rotateX, float rotateY)
a method to set the rotation / target of the camera
Parameters
fileLocation - the path name to the text file
Definition at line 535 of file Camera3.cpp.
References CameraXrotation, and CameraYrotation.
Referenced by scene2_SP2::Ending().
void Camera3::Update (double dt) virtual
To be called every frame. Camera will get user inputs and update its position and orientation.
Parameters
dt - frame time
Definition at line 151 of file Camera3.cpp.
References cameraMovement(), camType, COMMON, Vector3::Cross(), FIRST_PERSON, Application::IsKeyPressed(), Vector3::Length(), Vector3::Normalize(), Vector3::Normalized(), Camera::position, Reset(), rotateCamera(), Mtx44::SetToRotation(), Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by LoadingScreen::Update(), scene3SP2::Update(), scene2_SP2::Update(), and sceneSP2::Update().
Field Documentation
float Camera3::boundaryX private
Definition at line 72 of file Camera3.h.
Referenced by cameraMovement(), and Init().
float Camera3::boundaryZ private
Definition at line 72 of file Camera3.h.
Referenced by cameraMovement(), and Init().
float Camera3::cameraSpeed private
Definition at line 69 of file Camera3.h.
Referenced by cameraMovement(), and Init().
float Camera3::CameraXrotation private
Definition at line 66 of file Camera3.h.
Referenced by getCameraXrotation(), Init(), Reset(), rotateCamera(), and setRotation().
float Camera3::CameraYrotation private
Definition at line 67 of file Camera3.h.
Referenced by cameraMovement(), getCameraYrotation(), Init(), Reset(), rotateCamera(), and setRotation().
enum Camera3::CameraType Camera3::camType
Referenced by Init(), LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), sceneSP2::Init(), and Update().
float Camera3::crossHairRadius private
Definition at line 79 of file Camera3.h.
float Camera3::cursorCoordX
Definition at line 60 of file Camera3.h.
Referenced by LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), sceneSP2::Init(), and rotateCamera().
float Camera3::cursorCoordY
Definition at line 61 of file Camera3.h.
Referenced by LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), sceneSP2::Init(), and rotateCamera().
float Camera3::defaultCameraXrotation
Definition at line 39 of file Camera3.h.
Referenced by Init(), and Reset().
float Camera3::defaultCameraYrotation
Definition at line 39 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultPosition
Definition at line 36 of file Camera3.h.
Referenced by scene2_SP2::Ending(), Init(), Reset(), and scene3_SP2::Update().
Vector3 Camera3::defaultTarget
Definition at line 37 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultUp
Definition at line 38 of file Camera3.h.
Referenced by sceneSP2::animateTeleporting(), scene2_SP2::Ending(), Init(), Reset(), rotateCamera(), and scene3_SP2::Update().
Vector3 Camera3::invisibleCrossHair private
Definition at line 78 of file Camera3.h.
float Camera3::maxCameraXrotation private
Definition at line 67 of file Camera3.h.
Referenced by Init(), and rotateCamera().
float Camera3::minCameraXrotation private
Definition at line 67 of file Camera3.h.
Referenced by Init(), and rotateCamera().
vector<objectsForDisplay> Camera3::storage_of_objects
Definition at line 62 of file Camera3.h.
Referenced by cameraMovement(), scene3_SP2::Init(), scene2_SP2::Init(), sceneSP2::Init(), InitObjects(), sceneSP2::populateArea(), scene3_SP2::Render(), scene2_SP2::RenderArrow(), scene2_SP2::RenderAsteroid(), scene2_SP2::RenderBoxes(), sceneSP2::RenderBuilding(), sceneSP2::renderChunFei(), scene2_SP2::renderDeadPool(), scene2_SP2::RenderDiamond(), scene2_SP2::RenderFlyingVehicle(), scene2_SP2::RenderLandingVehicle(), scene2_SP2::RenderNPC(), scene2_SP2::RenderNumpad(), scene2_SP2::RenderSatellite(), scene3_SP2::renderSpaceShip(), sceneSP2::RenderSpaceShuttle(), scene2_SP2::RenderSpaceShuttle(), sceneSP2::RenderStation(), sceneSP2::Renderteleporter(), scene2_SP2::RenderVault(), scene3_SP2::renderWarp(), sceneSP2::teleport(), sceneSP2::Update(), and ~Camera3().
The documentation for this class was generated from the following files:
MyGraphics/Source/Camera3.h
MyGraphics/Source/Camera3.cpp