My Application: MaterialBuilder Class Reference
MaterialBuilder Class Reference
Provides methods to generate different materials.
#include <MaterialBuilder.h>
Static Public Member Functions
static Material GenerateBlinn (float shininess=1.f, float ambient=0.8, float diffuse=0.8f, float specular=0.5f)
generate similar properties to Blinn
static Material GenerateLambert (float shininess=1.f, float ambient=0.8f, float diffuse=0.8f, float specular=0.2f)
generate similar properties to Lambert
static Material GeneratePhong (float shininess=1.f, float ambient=0.8f, float diffuse=0.8f, float specular=0.9f)
generate similar properties to Phong
Detailed Description
Provides methods to generate different materials.
Class MaterialBuilder:
Definition at line 22 of file MaterialBuilder.h.
Member Function Documentation
Material MaterialBuilder::GenerateBlinn (float shininess = 1.f, float ambient = 0.8, float diffuse = 0.8f, float specular = 0.5f) static
generate similar properties to Blinn
Parameters
shininess - how bright will the object becomes
ambient - gradient of the object
diffuse - how the light diffuse on the object
specular - how spetacular the object will look like being shined upon
Returns
the material after it's properties have been set
Definition at line 16 of file MaterialBuilder.cpp.
References Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, and Component::Set().
Referenced by GenerateLambert(), GeneratePhong(), and scene3_SP2::Init().
Material MaterialBuilder::GenerateLambert (float shininess = 1.f, float ambient = 0.8f, float diffuse = 0.8f, float specular = 0.2f) static
generate similar properties to Lambert
Parameters
shininess - how bright will the object becomes
ambient - gradient of the object
diffuse - how the light diffuse on the object
specular - how spetacular the object will look like being shined upon
Returns
the material after it's properties have been set
Definition at line 41 of file MaterialBuilder.cpp.
References GenerateBlinn().
Referenced by sceneSP2::Init().
Material MaterialBuilder::GeneratePhong (float shininess = 1.f, float ambient = 0.8f, float diffuse = 0.8f, float specular = 0.9f) static
generate similar properties to Phong
Parameters
shininess - how bright will the object becomes
ambient - gradient of the object
diffuse - how the light diffuse on the object
specular - how spetacular the object will look like being shined upon
Returns
the material after it's properties have been set
Definition at line 60 of file MaterialBuilder.cpp.
References GenerateBlinn().
The documentation for this class was generated from the following files:
MyGraphics/Source/MaterialBuilder.h
MyGraphics/Source/MaterialBuilder.cpp