My Application: rot_civ Class Reference
rot_civ Class Reference
Inheirited from objectsForDisplay to reduce the amount of codes need to be written It can initialise Dialogues from a text file and speak from there It has it's own interaction boundary where the player must be located at to interact with him.
#include <rot_civ.h>
Public Member Functions
rot_civ ()
Default Constructor with some of it's values being initialised
~rot_civ ()
Destructor to delete the camera when it is destroyed
void InitDialogues (const char *fileLocation, Camera3 &camera)
Initialise dialogue and the scene's camera
void update (double dt)
update the interaction logic
string returnDialogue ()
get one of it's dialogues which is decided by a size_t variable
bool interaction ()
The interaction boundary of rot civ
void preventSpamming ()
Prevention of the dialogue from running to fast if player is holding 'E'
void reset ()
a method function that will reset the rot_civ's variables to it's default state
Public Member Functions inherited from objectsForDisplay
objectsForDisplay ()
Default Constructor
~objectsForDisplay ()
Destructor
void init (const char *fileLocation)
initialised it's values through text file reader
void init (Vector3 pos, float boundaryX, float boundaryZ, string name)
initialised it's variables by passing in parameter
bool boundaryCheck (const float &playerPosX, const float &playerPosZ)
the boundary check with the camera's position
float getObjectposX ()
get this object's X coordinate
float getObjectposY ()
get this object's Y coordinate
float getObjectposZ ()
get this object's Z coordinate
float getBoundaryRadiusX ()
get this object's X boundary range
float getBoundaryRadiusZ ()
get this object's Z boundary range
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Data Fields
vector< string > dialogues
Data Fields inherited from objectsForDisplay
Vector3 objectPos
Vector3 originalPos
Private Attributes
Camera3 * dub_camera
float interatingRadius
double time
size_t order_of_text
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Protected Attributes inherited from objectsForDisplay
float boundaryRadiusX
float boundaryRadiusZ
Protected Attributes inherited from GameObject
string Name_
Detailed Description
Inheirited from objectsForDisplay to reduce the amount of codes need to be written It can initialise Dialogues from a text file and speak from there It has it's own interaction boundary where the player must be located at to interact with him.
Class rot_civ:
Definition at line 26 of file rot_civ.h.
Constructor & Destructor Documentation
rot_civ::rot_civ ()
Default Constructor with some of it's values being initialised
Definition at line 18 of file rot_civ.cpp.
rot_civ::~rot_civ ()
Destructor to delete the camera when it is destroyed
Definition at line 29 of file rot_civ.cpp.
References dub_camera.
Member Function Documentation
void rot_civ::InitDialogues (const char * fileLocation, Camera3 & camera)
Initialise dialogue and the scene's camera
Parameters
fileLocation - To locate the text file for its dialogues
camera - a reference of the scene's camera
Definition at line 43 of file rot_civ.cpp.
References dialogues, and dub_camera.
Referenced by scene2_SP2::Init().
bool rot_civ::interaction ()
The interaction boundary of rot civ
Returns
false - if player is within its interacting boundary
true - if player is not within its interacting boundary
Definition at line 99 of file rot_civ.cpp.
References objectsForDisplay::boundaryRadiusX, objectsForDisplay::boundaryRadiusZ, dub_camera, Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), interatingRadius, objectsForDisplay::objectPos, order_of_text, Vector3::x, and Vector3::z.
Referenced by scene2_SP2::RenderRobot().
void rot_civ::preventSpamming ()
Prevention of the dialogue from running to fast if player is holding 'E'
Definition at line 116 of file rot_civ.cpp.
References dialogues, Application::IsKeyPressed(), order_of_text, and time.
Referenced by update().
void rot_civ::reset ()
a method function that will reset the rot_civ's variables to it's default state
Definition at line 133 of file rot_civ.cpp.
References order_of_text, and time.
string rot_civ::returnDialogue ()
get one of it's dialogues which is decided by a size_t variable
Returns
- One of it's dialogues
Definition at line 86 of file rot_civ.cpp.
References dialogues, and order_of_text.
Referenced by scene2_SP2::RenderRobot().
void rot_civ::update (double dt)
update the interaction logic
Parameters
dt - frame time
Definition at line 74 of file rot_civ.cpp.
References preventSpamming(), and time.
Referenced by scene2_SP2::Update().
Field Documentation
vector<string> rot_civ::dialogues
Definition at line 32 of file rot_civ.h.
Referenced by InitDialogues(), preventSpamming(), and returnDialogue().
Camera3* rot_civ::dub_camera private
Definition at line 42 of file rot_civ.h.
Referenced by InitDialogues(), interaction(), and ~rot_civ().
float rot_civ::interatingRadius private
Definition at line 43 of file rot_civ.h.
Referenced by interaction().
size_t rot_civ::order_of_text private
Definition at line 45 of file rot_civ.h.
Referenced by interaction(), preventSpamming(), reset(), and returnDialogue().
double rot_civ::time private
Definition at line 44 of file rot_civ.h.
Referenced by preventSpamming(), reset(), and update().
The documentation for this class was generated from the following files:
MyGraphics/Source/rot_civ.h
MyGraphics/Source/rot_civ.cpp