My Application: NPC Class Reference
NPC Class Reference
Inheirited from GameObject It has a text reader file to input it's dialogue
#include <NPC.h>
Public Member Functions
NPC ()
Default Constructor
~NPC ()
Destructor
void Init (string name, short NumberofDialogue, Vector3 pos, float boundaryX, float boundaryZ, Camera3 &camera_address, const char *fileLocation)
initialised it's values through text file reader as well as some other variables initialised through function parameters needed for NPC class to work
float NPC_getposition_x ()
get this object's X coordinate
float NPC_getposition_z ()
get this object's y coordinate
float NPC_getposition_y ()
get this object's y coordinate
bool boundschecking (const float &bounds_x, const float &bounds_z)
bounds checking for interaction
void update (double dt)
update some variables at every frame
string getDialogue (bool reset)
get this object's dialogue
bool interaction ()
to check if player is within range to interact with this object
bool quest_given ()
to check if player has been given a quest from this npc object
string quest_complete ()
returns dialogue for the npc when quest is complete
short get_LineOfDialogue ()
to get which line of dialogue the npc object should be currently displaying
void reset ()
to reset all npc dialogue when scene resets
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Private Attributes
Vector3 NPC_pos
vector< string > Dialogues
Camera3 * cam_pointer
float bound_x
float bound_z
int dialogue_switch
bool dialogue_reset
double time
bool has_interacted
float text_delay
bool dialogue_finish
int stage
bool quest_complete_stage
bool quest_complete_delay
short line_of_dialogue
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Protected Attributes inherited from GameObject
string Name_
Detailed Description
Inheirited from GameObject It has a text reader file to input it's dialogue
Class NPC:
Definition at line 25 of file NPC.h.
Constructor & Destructor Documentation
NPC::NPC ()
Default Constructor
Definition at line 17 of file NPC.cpp.
NPC::~NPC ()
Destructor
Definition at line 27 of file NPC.cpp.
Member Function Documentation
bool NPC::boundschecking (const float & bounds_x, const float & bounds_z)
bounds checking for interaction
Returns
true player is in range of interaction
false player is not in range of interaction
Definition at line 198 of file NPC.cpp.
References bound_x, bound_z, NPC_getposition_x(), and NPC_getposition_z().
Referenced by interaction().
short NPC::get_LineOfDialogue ()
to get which line of dialogue the npc object should be currently displaying
Returns
the line number of the dialogue as a short
Definition at line 286 of file NPC.cpp.
References dialogue_switch.
Referenced by scene2_SP2::BoxesAnimation(), and scene2_SP2::NPCAnimation().
string NPC::getDialogue (bool reset)
get this object's dialogue
Parameters
reset - to reset the dialogue if player moves out of range
Returns
- dialogue for object in the form of a string
Definition at line 131 of file NPC.cpp.
References dialogue_finish, dialogue_reset, dialogue_switch, Dialogues, has_interacted, line_of_dialogue, reset(), text_delay, and time.
Referenced by sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), and scene2_SP2::RenderVault().
void NPC::Init (string name, short NumberofDialogue, Vector3 pos, float boundaryX, float boundaryZ, Camera3 & camera_address, const char * fileLocation)
initialised it's values through text file reader as well as some other variables initialised through function parameters needed for NPC class to work
Parameters
name - name of object
NumberofDialogue - number of lines of dialogue the NPC has
pos - Coodinates of object
boundaryX - X axis bounds for object
boundaryZ - Z axis bounds for object
camera_address - camera object
fileLocation - the path name to the text file
Definition at line 51 of file NPC.cpp.
References bound_x, bound_z, cam_pointer, dialogue_finish, dialogue_reset, dialogue_switch, Dialogues, has_interacted, line_of_dialogue, GameObject::Name_, NPC_pos, quest_complete_delay, quest_complete_stage, stage, text_delay, and time.
Referenced by scene2_SP2::Init(), and sceneSP2::Init().
bool NPC::interaction ()
to check if player is within range to interact with this object
Returns
true player is in range of interacting with this object
false player is not in range of interacting with this object
Definition at line 176 of file NPC.cpp.
References boundschecking(), cam_pointer, Camera3::getCameraXcoord(), Camera3::getCameraZcoord(), and has_interacted.
Referenced by scene2_SP2::BoxesAnimation(), sceneSP2::headanimation(), scene2_SP2::NPCAnimation(), sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), and scene2_SP2::RenderVault().
float NPC::NPC_getposition_x ()
get this object's X coordinate
Returns
- X coordinate of the object
Definition at line 95 of file NPC.cpp.
References NPC_pos, and Vector3::x.
Referenced by boundschecking(), sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), and scene2_SP2::RenderVault().
float NPC::NPC_getposition_y ()
get this object's y coordinate
Returns
- y coordinate of the object
Definition at line 117 of file NPC.cpp.
References NPC_pos, and Vector3::y.
Referenced by sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), and scene2_SP2::RenderVault().
float NPC::NPC_getposition_z ()
get this object's y coordinate
Returns
- y coordinate of the object
Definition at line 106 of file NPC.cpp.
References NPC_pos, and Vector3::z.
Referenced by boundschecking(), sceneSP2::renderChunFei(), sceneSP2::RenderNPC(), scene2_SP2::RenderNPC(), and scene2_SP2::RenderVault().
string NPC::quest_complete ()
returns dialogue for the npc when quest is complete
Returns
dialogue for the npc when quest is complete
Definition at line 262 of file NPC.cpp.
References Dialogues, Application::IsKeyPressed(), line_of_dialogue, and quest_complete_stage.
Referenced by sceneSP2::renderChunFei(), and sceneSP2::RenderNPC().
bool NPC::quest_given ()
to check if player has been given a quest from this npc object
Returns
true quest has been given
false quest has not been given
Definition at line 251 of file NPC.cpp.
References dialogue_finish.
Referenced by sceneSP2::Update().
void NPC::reset ()
to reset all npc dialogue when scene resets
Definition at line 231 of file NPC.cpp.
References dialogue_finish, dialogue_reset, dialogue_switch, has_interacted, quest_complete_delay, quest_complete_stage, stage, and time.
Referenced by getDialogue(), sceneSP2::reset(), and update().
void NPC::update (double dt)
update some variables at every frame
Parameters
dt - delta time
Definition at line 216 of file NPC.cpp.
References Application::IsKeyPressed(), reset(), and time.
Referenced by scene2_SP2::Update(), and sceneSP2::Update().
Field Documentation
float NPC::bound_x private
Definition at line 47 of file NPC.h.
Referenced by boundschecking(), and Init().
float NPC::bound_z private
Definition at line 47 of file NPC.h.
Referenced by boundschecking(), and Init().
Camera3* NPC::cam_pointer private
Definition at line 46 of file NPC.h.
Referenced by Init(), and interaction().
bool NPC::dialogue_finish private
Definition at line 53 of file NPC.h.
Referenced by getDialogue(), Init(), quest_given(), and reset().
bool NPC::dialogue_reset private
Definition at line 49 of file NPC.h.
Referenced by getDialogue(), Init(), and reset().
int NPC::dialogue_switch private
Definition at line 48 of file NPC.h.
Referenced by get_LineOfDialogue(), getDialogue(), Init(), and reset().
vector<string> NPC::Dialogues private
Definition at line 45 of file NPC.h.
Referenced by getDialogue(), Init(), and quest_complete().
bool NPC::has_interacted private
Definition at line 51 of file NPC.h.
Referenced by getDialogue(), Init(), interaction(), and reset().
short NPC::line_of_dialogue private
Definition at line 57 of file NPC.h.
Referenced by getDialogue(), Init(), and quest_complete().
Vector3 NPC::NPC_pos private
Definition at line 44 of file NPC.h.
Referenced by Init(), NPC_getposition_x(), NPC_getposition_y(), and NPC_getposition_z().
bool NPC::quest_complete_delay private
Definition at line 56 of file NPC.h.
Referenced by Init(), and reset().
bool NPC::quest_complete_stage private
Definition at line 55 of file NPC.h.
Referenced by Init(), quest_complete(), and reset().
int NPC::stage private
Definition at line 54 of file NPC.h.
Referenced by Init(), and reset().
float NPC::text_delay private
Definition at line 52 of file NPC.h.
Referenced by getDialogue(), and Init().
double NPC::time private
Definition at line 50 of file NPC.h.
Referenced by getDialogue(), Init(), reset(), and update().
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/NPC.cpp