My Application: LoadingScreen Class Reference
LoadingScreen Class Reference
Just Rendering of the Loading Screen to ease the boredom of player when initialising other scenes.
#include <LoadingScreen.h>
Public Member Functions
LoadingScreen (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
~LoadingScreen ()
destructor
virtual void Init ()
initializing whatever is needed for the scene
virtual void Update (double dt)
where the logic of the game is, and update
virtual void Render ()
where the rendering of all the stuff we needed will be here
virtual void Exit ()
cleans up the scene
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_LIGHTBALL, GEO_COMIC_TEXT, GEO_LOADING_SCREEN_TITLE,
GEO_LOADING_DOGE, GEO_LOADING_BREATHING_CAT, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
rendering of the meshes
void RenderText (Mesh *mesh, std::string text, Color color)
rendering of the texts using quads
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
rendering of the texts using quads on screen
void RenderImageOnScreen (Mesh *mesh, float size, float x, float y)
rendering of image using quad on screen
void initLoadingHints (const char *fileName)
initialising the hints from a text file
Private Attributes
bool on_light
Light light [1]
float LSPEED = 10.f
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
double framePerSecond
float screenWidth
float screenHeight
vector< string > loadingHints
float percentage
Detailed Description
Just Rendering of the Loading Screen to ease the boredom of player when initialising other scenes.
Class LoadingScreen:
Definition at line 26 of file LoadingScreen.h.
Member Enumeration Documentation
enum LoadingScreen::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LIGHTBALL
GEO_COMIC_TEXT
GEO_LOADING_SCREEN_TITLE
GEO_LOADING_DOGE
GEO_LOADING_BREATHING_CAT
NUM_GEOMETRY
Definition at line 28 of file LoadingScreen.h.
enum LoadingScreen::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 39 of file LoadingScreen.h.
Constructor & Destructor Documentation
LoadingScreen::LoadingScreen (float screenwidth, float screenheight)
constructor with 2 arguments to store the width and height of the screen
Parameters
screenwidth - width of the screen
screenheight - height of the screen
Definition at line 26 of file LoadingScreen.cpp.
LoadingScreen::~LoadingScreen ()
destructor
Definition at line 35 of file LoadingScreen.cpp.
Member Function Documentation
void LoadingScreen::Exit () virtual
cleans up the scene
Implements Scene.
Definition at line 283 of file LoadingScreen.cpp.
References m_programID, and m_vertexArrayID.
void LoadingScreen::Init () virtual
initializing whatever is needed for the scene
Implements Scene.
Definition at line 44 of file LoadingScreen.cpp.
References camera, Camera3::camType, Light::color, Light::cosCutoff, Light::cosInner, Camera3::cursorCoordX, Camera3::cursorCoordY, Math::DegreeToRadian(), Light::exponent, Camera3::FIRST_PERSON, framePerSecond, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_COMIC_TEXT, GEO_LOADING_BREATHING_CAT, GEO_LOADING_DOGE, GEO_LOADING_SCREEN_TITLE, Camera3::Init(), initLoadingHints(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, on_light, percentage, Light::position, Light::power, projectionStack, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void LoadingScreen::initLoadingHints (const char * fileName) private
initialising the hints from a text file
Parameters
fileName - path name to the file's location
Definition at line 424 of file LoadingScreen.cpp.
References loadingHints.
Referenced by Init().
void LoadingScreen::Render () virtual
where the rendering of all the stuff we needed will be here
Implements Scene.
Definition at line 230 of file LoadingScreen.cpp.
References camera, GEO_COMIC_TEXT, GEO_LOADING_BREATHING_CAT, GEO_LOADING_DOGE, GEO_LOADING_SCREEN_TITLE, MS::LoadIdentity(), loadingHints, MS::LookAt(), meshList, percentage, Camera::position, Math::RandIntMinMax(), RenderImageOnScreen(), RenderTextOnScreen(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Camera::target, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void LoadingScreen::RenderImageOnScreen (Mesh * mesh, float size, float x, float y) private
rendering of image using quad on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 394 of file LoadingScreen.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render().
void LoadingScreen::renderMesh (Mesh * mesh, bool enableLight) private
rendering of the meshes
Parameters
mesh - the specific mesh
enableLight - to enable lighting on the object
Definition at line 182 of file LoadingScreen.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderImageOnScreen().
void LoadingScreen::RenderText (Mesh * mesh, std::string text, Color color) private
rendering of the texts using quads
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
Definition at line 299 of file LoadingScreen.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void LoadingScreen::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
rendering of the texts using quads on screen
Parameters
mesh - a pointer to the specific mesh
text - the text that needs to be rendered
color - the color of the text
size - size of the text
x - x coordinate of the text
y - y coordinate of the text
Definition at line 339 of file LoadingScreen.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void LoadingScreen::Update (double dt) virtual
where the logic of the game is, and update
Parameters
dt - time frame
Implements Scene.
Definition at line 168 of file LoadingScreen.cpp.
References camera, framePerSecond, and Camera3::Update().
Field Documentation
Camera3 LoadingScreen::camera private
Definition at line 88 of file LoadingScreen.h.
Referenced by Init(), Render(), and Update().
double LoadingScreen::framePerSecond private
Definition at line 96 of file LoadingScreen.h.
Referenced by Init(), and Update().
Light LoadingScreen::light[1] private
Definition at line 79 of file LoadingScreen.h.
Referenced by Init().
vector<string> LoadingScreen::loadingHints private
Definition at line 99 of file LoadingScreen.h.
Referenced by initLoadingHints(), and Render().
float LoadingScreen::LSPEED = 10.f private
Definition at line 80 of file LoadingScreen.h.
unsigned LoadingScreen::m_parameters[U_TOTAL] private
Definition at line 86 of file LoadingScreen.h.
Referenced by Init(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned LoadingScreen::m_programID private
Definition at line 85 of file LoadingScreen.h.
Referenced by Exit(), and Init().
unsigned LoadingScreen::m_vertexArrayID private
Definition at line 82 of file LoadingScreen.h.
Referenced by Exit(), and Init().
Mesh* LoadingScreen::meshList[NUM_GEOMETRY] private
Definition at line 83 of file LoadingScreen.h.
Referenced by Init(), and Render().
MS LoadingScreen::modelStack private
Definition at line 90 of file LoadingScreen.h.
Referenced by RenderImageOnScreen(), renderMesh(), RenderText(), and RenderTextOnScreen().
bool LoadingScreen::on_light private
Definition at line 78 of file LoadingScreen.h.
Referenced by Init().
float LoadingScreen::percentage private
Definition at line 102 of file LoadingScreen.h.
Referenced by Init(), and Render().
MS LoadingScreen::projectionStack private
Definition at line 90 of file LoadingScreen.h.
Referenced by Init(), RenderImageOnScreen(), renderMesh(), RenderText(), and RenderTextOnScreen().
float LoadingScreen::screenHeight private
Definition at line 97 of file LoadingScreen.h.
Referenced by Init().
float LoadingScreen::screenWidth private
Definition at line 97 of file LoadingScreen.h.
Referenced by Init().
MS LoadingScreen::viewStack private
Definition at line 90 of file LoadingScreen.h.
Referenced by Render(), RenderImageOnScreen(), renderMesh(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/LoadingScreen.h
MyGraphics/Source/LoadingScreen.cpp