My Application: StationScene Class Reference
StationScene Class Reference
Inheirited from GameObject It will have the collisiont check and position. And it's own dialogues and interactions boundary
#include <StationScene.h>
Public Member Functions
StationScene ()
a default constructor, with all variables becoming default value
~StationScene ()
void Init (Camera3 &camera_address)
init the variable that are needed
void update (double dt)
updating the time
short getQuestStage ()
to check to check whether what stage his in to open door
short getCard1 ()
enable to collect card if is within the boundary
short getCard2 ()
enable to collect card if is within the boundary
bool getCardText ()
show text only with the interacting boundary
short openSasame ()
to check whether the player taken 2 card and if 2 card is taken door can now be open after you press E
bool roomLight ()
to check whether the player in within it's interacting boundary to toggle the light
bool switchText ()
show text only with the interacting boundary
void reset ()
reset the entire room interaction
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Destructor - destroys GameObject and decrease count_ by 1 when it goes out of scope or deleted.
string getName (void)
Get the string kName and does not take in any argument.
Private Attributes
Camera3 * cam_pointer
float time
bool questActive
bool questComplete
bool card1
bool card2
short count
bool doorOpened
bool switchLightOn
float delay
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get the value of count_.
Protected Member Functions inherited from GameObject
GameObject (const string &str)
Constructor with 1 string argument - construct an object with a name assigned to it and add 1 to the count_.
Protected Attributes inherited from GameObject
string Name_
Detailed Description
Inheirited from GameObject It will have the collisiont check and position. And it's own dialogues and interactions boundary
Author
SEETOO WEI JIE VICTOR
email: 150452J.nyp.edu.sg
Definition at line 30 of file StationScene.h.
Constructor & Destructor Documentation
StationScene::StationScene ()
a default constructor, with all variables becoming default value
Definition at line 9 of file StationScene.cpp.
StationScene::~StationScene ()
Definition at line 13 of file StationScene.cpp.
Member Function Documentation
short StationScene::getCard1 ()
enable to collect card if is within the boundary
Returns
- 1 when is taken
- 0 if is not taken
Definition at line 46 of file StationScene.cpp.
References cam_pointer, card1, count, Application::IsKeyPressed(), Camera::position, questActive, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::RenderStation().
short StationScene::getCard2 ()
enable to collect card if is within the boundary
Returns
- 1 when is taken
- 0 if is not taken
Definition at line 77 of file StationScene.cpp.
References cam_pointer, card2, count, Application::IsKeyPressed(), Camera::position, questActive, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::RenderStation().
bool StationScene::getCardText ()
show text only with the interacting boundary
Returns
- true if the player is inside it's interacting boundary
- false if the player is outside it's interacting boundary
Definition at line 108 of file StationScene.cpp.
References cam_pointer, card1, card2, Camera::position, questActive, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::RenderStation().
short StationScene::getQuestStage ()
to check to check whether what stage his in to open door
Returns
- 1 to tell player press E to open the door
- 2 to tell player that 2 keycard is needed to open
- 3 to spawn the card into the world
Definition at line 136 of file StationScene.cpp.
References cam_pointer, Application::IsKeyPressed(), Camera::position, questActive, questComplete, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::RenderStation().
void StationScene::Init (Camera3 & camera_address)
init the variable that are needed
Definition at line 23 of file StationScene.cpp.
References cam_pointer, card1, card2, delay, doorOpened, questActive, questComplete, switchLightOn, and time.
Referenced by sceneSP2::Init().
short StationScene::openSasame ()
to check whether the player taken 2 card and if 2 card is taken door can now be open after you press E
Returns
- 1 if the player has not open the door
- 2 if the player has open the door
Definition at line 177 of file StationScene.cpp.
References cam_pointer, card1, card2, doorOpened, Application::IsKeyPressed(), Camera::position, questComplete, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), sceneSP2::RenderStation(), and sceneSP2::Update().
void StationScene::reset ()
reset the entire room interaction
Definition at line 271 of file StationScene.cpp.
References card1, card2, doorOpened, questActive, questComplete, and switchLightOn.
Referenced by sceneSP2::reset().
bool StationScene::roomLight ()
to check whether the player in within it's interacting boundary to toggle the light
Returns
- true if the player is inside it's interacting boundary and whether E is press switch ON the light
- false if the player is inside it's interacting boundary and whether E is press switch off the light
Definition at line 211 of file StationScene.cpp.
References cam_pointer, delay, Application::IsKeyPressed(), Camera::position, switchLightOn, time, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::Update().
bool StationScene::switchText ()
show text only with the interacting boundary
Returns
- true if the player is inside it's interacting boundary
- false if the player is outside it's interacting boundary
Definition at line 236 of file StationScene.cpp.
References cam_pointer, Camera::position, switchLightOn, Vector3::x, and Vector3::z.
Referenced by sceneSP2::Init(), and sceneSP2::RenderStation().
void StationScene::update (double dt)
updating the time
Parameters
dt - frame time
Definition at line 260 of file StationScene.cpp.
References time.
Referenced by sceneSP2::Update().
Field Documentation
Camera3* StationScene::cam_pointer private
Definition at line 49 of file StationScene.h.
Referenced by getCard1(), getCard2(), getCardText(), getQuestStage(), Init(), openSasame(), roomLight(), and switchText().
bool StationScene::card1 private
Definition at line 53 of file StationScene.h.
Referenced by getCard1(), getCardText(), Init(), openSasame(), and reset().
bool StationScene::card2 private
Definition at line 54 of file StationScene.h.
Referenced by getCard2(), getCardText(), Init(), openSasame(), and reset().
short StationScene::count private
Definition at line 55 of file StationScene.h.
Referenced by getCard1(), and getCard2().
float StationScene::delay private
Definition at line 58 of file StationScene.h.
Referenced by Init(), and roomLight().
bool StationScene::doorOpened private
Definition at line 56 of file StationScene.h.
Referenced by Init(), openSasame(), and reset().
bool StationScene::questActive private
Definition at line 51 of file StationScene.h.
Referenced by getCard1(), getCard2(), getCardText(), getQuestStage(), Init(), and reset().
bool StationScene::questComplete private
Definition at line 52 of file StationScene.h.
Referenced by getQuestStage(), Init(), openSasame(), and reset().
bool StationScene::switchLightOn private
Definition at line 57 of file StationScene.h.
Referenced by Init(), reset(), roomLight(), and switchText().
float StationScene::time private
Definition at line 50 of file StationScene.h.
Referenced by Init(), roomLight(), and update().
The documentation for this class was generated from the following files:
MyGraphics/Source/StationScene.h
MyGraphics/Source/StationScene.cpp