My Application: MyGraphics/Source/LoadOBJ.cpp File Reference
LoadOBJ.cpp File Reference
#include <iostream>
#include <fstream>
#include <map>
#include "LoadOBJ.h"
Data Structures
struct PackedVertex
vertex with it's properties
Functions
bool LoadOBJ (const char *file_path, std::vector< Position > &out_vertices, std::vector< TexCoord > &out_uvs, std::vector< Vector3 > &out_normals)
loading of object file from external source
bool getSimilarVertexIndex_fast (PackedVertex &packed, std::map< PackedVertex, unsigned short > &VertexToOutIndex, unsigned short &result)
Copying of vertex
void IndexVBO (std::vector< Position > &in_vertices, std::vector< TexCoord > &in_uvs, std::vector< Vector3 > &in_normals, std::vector< unsigned > &out_indices, std::vector< Vertex > &out_vertices)
indexing the vertices
Function Documentation
bool getSimilarVertexIndex_fast (PackedVertex & packed, std::map< PackedVertex, unsigned short > & VertexToOutIndex, unsigned short & result)
Copying of vertex
Parameters
packed - a referenced of PackedVertex
out_vertices - a referenced vector of vertices
out_uvs - a referenced vector of texture coordinates
Returns
false - if copying finished
true - if not copying finished
Definition at line 165 of file LoadOBJ.cpp.
Referenced by IndexVBO().
void IndexVBO (std::vector< Position > & in_vertices, std::vector< TexCoord > & in_uvs, std::vector< Vector3 > & in_normals, std::vector< unsigned > & out_indices, std::vector< Vertex > & out_vertices)
indexing the vertices
Parameters
in_vertices - a referenced vector of vertices
in_uvs - a referenced vector of texture coordinates
in_normals - a referenced vector of normals
out_indices - a referenced vector of indices
out_vertices - a referenced vector of vertices
Definition at line 194 of file LoadOBJ.cpp.
References getSimilarVertexIndex_fast(), Vertex::pos, Position::Set(), TexCoord::Set(), and Vertex::texCoord.
Referenced by MeshBuilder::GenerateOBJ().
bool LoadOBJ (const char * file_path, std::vector< Position > & out_vertices, std::vector< TexCoord > & out_uvs, std::vector< Vector3 > & out_normals)
loading of object file from external source
Parameters
file_path - the location of the file
out_vertices - a referenced vector of vertices
out_uvs - a referenced vector of texture coordinates
out_normals - a referenced vector of normals
Returns
false - if loading object file does not work
true - if loading object file works
Definition at line 21 of file LoadOBJ.cpp.
References TexCoord::u, TexCoord::v, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
Referenced by MeshBuilder::GenerateOBJ().