My Application: MyGraphics/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
#include "MeshBuilder.h"
#include <GL\glew.h>
#include <vector>
#include "MyMath.h"
#include "LoadOBJ.h"
Functions
float SphereX (float phi, float theta)
get the x coordinate of the vertice based on a circular motion
float SphereY (float phi, float theta)
get the y coordinate of the vertice based on a circular motion
float SphereZ (float phi, float theta)
get the z coordinate of the vertice based on a circular motion
Function Documentation
float SphereX (float phi, float theta)
get the x coordinate of the vertice based on a circular motion
Parameters
phi - an angle
theta - an angle
Returns
x coordinate of the vertice
Definition at line 195 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float SphereY (float phi, float theta)
get the y coordinate of the vertice based on a circular motion
Parameters
phi - an angle
theta - an angle
Returns
y coordinate of the vertice
Definition at line 211 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float SphereZ (float phi, float theta)
get the z coordinate of the vertice based on a circular motion
Parameters
phi - an angle
theta - an angle
Returns
z coordinate of the vertice
Definition at line 227 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().