My Application: MyGraphics/Source/shader.cpp File Reference
shader.cpp File Reference
#include <stdio.h>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <stdlib.h>
#include <string.h>
#include <GL/glew.h>
#include "shader.hpp"
Functions
GLuint LoadShaders (const char *vertex_file_path, const char *fragment_file_path)
loading of the vertex shaders and fragment shaders from external source
Function Documentation
GLuint LoadShaders (const char * vertex_file_path, const char * fragment_file_path)
loading of the vertex shaders and fragment shaders from external source
Parameters
vertex_file_path - path name to the vertex file location
fragment_file_path - path name to the fragment file location
Definition at line 25 of file shader.cpp.
Referenced by LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), and sceneSP2::Init().