My Application: MyGraphics/Source/shader.hpp File Reference
shader.hpp File Reference
Loading of shaders Taken from Mr Tang's framework
Functions
GLuint LoadShaders (const char *vertex_file_path, const char *fragment_file_path)
loading of the vertex shaders and fragment shaders from external source
Detailed Description
Loading of shaders Taken from Mr Tang's framework
Author
Lee Sek Heng
email: 150629Z.nyp.edu.sg
Definition in file shader.hpp.
Function Documentation
GLuint LoadShaders (const char * vertex_file_path, const char * fragment_file_path)
loading of the vertex shaders and fragment shaders from external source
Parameters
vertex_file_path - path name to the vertex file location
fragment_file_path - path name to the fragment file location
Definition at line 25 of file shader.cpp.
Referenced by LoadingScreen::Init(), scene3SP2::Init(), scene3_SP2::Init(), scene2_SP2::Init(), and sceneSP2::Init().