My Application: Component Struct Reference
Component Struct Reference
Defines material's colour.
#include <Material.h>
Public Member Functions
Component (float r=0.1f, float g=0.1f, float b=1.0f)
void Set (float r, float g, float b)
Data Fields
float r
float g
float b
Detailed Description
Defines material's colour.
struct Component:
Definition at line 20 of file Material.h.
Constructor & Destructor Documentation
Component::Component (float r = 0.1f, float g = 0.1f, float b = 1.0f) inline
Definition at line 23 of file Material.h.
References Set().
Member Function Documentation
void Component::Set (float r, float g, float b) inline
Definition at line 24 of file Material.h.
References b, g, and r.
Referenced by Component(), MaterialBuilder::GenerateBlinn(), and sceneSP2::Init().
Field Documentation
float Component::b
Definition at line 22 of file Material.h.
Referenced by Set().
float Component::g
Definition at line 22 of file Material.h.
Referenced by Set().
float Component::r
Definition at line 22 of file Material.h.
Referenced by LoadingScreen::renderMesh(), scene3SP2::renderMesh(), scene3_SP2::renderMesh(), sceneSP2::renderMesh(), scene2_SP2::renderMesh(), and Set().
The documentation for this struct was generated from the following file:
MyGraphics/Source/Material.h